-- java questions
INSERT INTO questions (id, question, option1, option2, option3, option4, correct_answers, is_multiple_choice, category) VALUES
(1, 'How many pillars of OOPs java has?', '3', '4', '5', '6', '2', 0, 'java'),
(2, 'What is the default value of a boolean variable in Java?', '1', '0', 'Null', '0', '2', 0, 'java'),
(3, 'Which of the following is not a valid data type in Java?', 'int', 'float', 'double', 'real', '3', 0, 'java'),
(4, 'What is the main purpose of the final keyword in Java?', 'To declare a constant', 'To prevent method overriding', 'To prevent inheritance', 'All of the above', '3', 0, 'java'),
(5, 'Which of the following methods can be used to start a thread in Java?', 'run()', 'start()', 'execute()', 'begin()', '1', 0, 'java'),
(6, 'Output: int x = 10; int y = 20; System.out.println(x + y + "10");', '3010', '2010', '30', '210', '0', 0, 'java'),
(7, 'What is the main entry point of a Java application?', 'main()', 'start()', 'init()', 'run()', '0', 0, 'java'),
(8, 'Which keyword is used to create a class in Java?', 'class', 'create', 'new', 'define', '0', 0, 'java'),
(9, 'Which of the following are primitive data types in Java?', 'int', 'String', 'boolean', 'char', '0,2,3', 1, 'java'),
(10, 'Which of the following are valid keywords in Java?', 'static', 'void', 'main', 'function', '0,1,2', 1, 'java'),
(11, 'Which of the following are valid ways to create an object in Java?', 'Using new keyword', 'Using factory methods', 'Using cloning', 'Using constructors', '0,1,3', 1, 'java'),
(12, 'Which of the following can be used to handle exceptions in Java?', 'try-catch', 'throw', 'throws', 'finally', '0,1,2,3', 1, 'java'),
(13, 'Which of the following are features of Java?', 'Platform independence', 'Object-oriented', 'Automatic garbage collection', 'Pointer arithmetic', '0,1,2', 1, 'java'),
(14, 'Which of the following are types of loops in Java?', 'for', 'while', 'do-while', 'foreach', '0,1,2,3', 1, 'java'),
(15, 'Which of the following are collection interfaces in Java?', 'List', 'Set', 'Map', 'Array', '0,1,2', 1, 'java'),
(16, 'Which of the following access modifiers are available in Java?', 'public', 'private', 'protected', 'friend', '0,1,2', 1, 'java'),
(17, 'Which of the following are valid ways to declare an array in Java?', 'int[] arr;', 'int arr[];', 'int arr = new int[5];', 'int[] arr = new int[];', '0,1,2', 1, 'java'),
(18, 'Which of the following statements about interfaces are 1?', 'Interfaces can extend other interfaces', 'An interface can contain method implementations', 'A class can implement multiple interfaces', 'Interfaces cannot have instance variables', '0,2,3', 1, 'java'),
(19, 'Which of the following are valid Java annotations?', '@Override', '@Entity', '@Service', '@Main', '0,1,2', 1, 'java'),
(20, 'Which of the following are valid ways to implement a thread in Java?', 'Extending Thread class', 'Implementing Runnable interface', 'Using ExecutorService', 'Creating a method', '0,1,2', 1, 'java'),
(21, 'Which of the following statements about the Java Collections Framework are 1?', 'It provides data structures for storing groups of objects', 'It supports sorting and searching operations', 'All collections implement the Collection interface', 'Collections can be synchronized', '0,1,2,3', 1, 'java'),
(22, 'Which of the following are valid Java stream operations?', 'filter()', 'map()', 'reduce()', 'collect()', '0,1,2,3', 1, 'java'),
(23, 'Which of the following are commonly used Java frameworks?', 'Spring', 'Hibernate', 'JSF', 'Angular', '0,1,2', 1, 'java'),
(24, 'Which of the following statements about Java inheritance are 1?', 'Java supports multiple inheritance', 'A class can only extend one class', 'Subclasses can override methods of superclasses', 'Constructors are inherited', '1,2', 1, 'java'),
(25, 'Which of the following are valid types of exceptions in Java?', 'Checked exceptions', 'Unchecked exceptions', 'Errors', 'Runtime exceptions', '0,1,2,3', 1, 'java'),
(26, 'Which of the following statements about Java memory management are 1?', 'Memory allocation is done at runtime', 'Garbage collector automatically deallocates memory', 'Memory leaks can occur', 'Finalizers can be used to clean up resources', '0,1,2,3', 1, 'java'),
(27, 'Which of the following are types of Java applications?', 'Standalone applications', 'Web applications', 'Mobile applications', 'Console applications', '0,1,2,3', 1, 'java'),
(28, 'What does JVM stand for?', 'Java Variable Machine', 'Java Virtual Machine', 'Java Visual Machine', 'Java Value Machine', '1', 0, 'java'),
(29, 'Which of the following is a valid way to declare an array in Java?', 'int[] arr;', 'int arr[];', 'Both 1 and 2', 'None of the above', '2', 0, 'java'),
(30, 'What is the default value of a boolean in Java?', '1', '0', '0', '1', '1', 0, 'java'),
(31, 'Which of the following is not a valid access modifier in Java?', 'public', 'protected', 'private', 'internal', '3', 0, 'java'),
(32, 'What does the \'static\' keyword indicate in Java?', 'Instance variable', 'Class variable', 'Local variable', 'Global variable', '1', 0, 'java'),
(33, 'Which of the following can throw an exception in Java?', 'Runtime', 'Checked', 'Unchecked', 'All of the above', '3', 0, 'java'),
(34, 'What is the purpose of the \'this\' keyword in Java?', 'To refer to the current instance', 'To call a constructor', 'To access static members', 'None of the above', '0', 0, 'java'),
(35, 'Which method is used to compare two strings in Java?', 'compare()', 'equals()', '==', 'compareTo()', '1', 0, 'java'),
(36, 'What is the output of \'System.out.println(1 + 2 + "3");\'?', '33', '6', '15', 'Error', '1', 0, 'java'),
(37, 'Which of the following is a valid constructor in Java?', 'ClassName()', 'void ClassName()', 'ClassName;', 'new ClassName()', '0', 0, 'java'),
(38, 'What does the \'final\' keyword do in Java?', 'Makes a variable constant', 'Prevents method overriding', 'Prevents inheritance', 'All of the above', '3', 0, 'java'),
(39, 'What is the size of an int in Java?', '2 bytes', '4 bytes', '8 bytes', '16 bytes', '1', 0, 'java'),
(40, 'Which of the following collections is ordered in Java?', 'HashSet', 'TreeSet', 'ArrayList', 'HashMap', '2', 0, 'java'),
(41, 'What is a Java package?', 'A collection of classes', 'A way to organize classes', 'Both 1 and 2', 'None of the above', '2', 0, 'java'),
(42, 'Which of the following is used to create a thread in Java?', 'Runnable', 'Thread', 'Both 1 and 2', 'Process', '2', 0, 'java'),
(43, 'What does the \'super\' keyword do in Java?', 'Access parent class methods', 'Call a superclass constructor', 'Both 1 and 2', 'None of the above', '2', 0, 'java'),
(44, 'Which annotation is used to mark a method as an override in Java?', '@Override', '@OverrideMethod', '@OverrideFunc', '@Super', '0', 0, 'java'),
(45, 'What does the term \'polymorphism\' refer to in Java?', 'Multiple forms of methods', 'Overloading methods', 'Overriding methods', 'All of the above', '3', 0, 'java'),
(46, 'What is a lambda expression in Java?', 'A way to define anonymous functions', 'A new data type', 'An exception', 'None of the above', '0', 0, 'java'),
(47, 'Which of the following is not a primitive data type in Java?', 'int', 'float', 'String', 'boolean', '2', 0, 'java'),
(48, 'What is the main purpose of the \'try-catch\' block in Java?', 'To handle exceptions', 'To define a loop', 'To create threads', 'None of the above', '0', 0, 'java'),
(49, 'Which of the following interfaces allows you to iterate over a collection in Java?', 'Iterable', 'Collection', 'Iterator', 'All of the above', '3', 0, 'java'),
(50, 'Which framework is commonly used for building web applications in Java?', 'Spring', 'Hibernate', 'Struts', 'All of the above', '3', 0, 'java'),
(51, 'What is the purpose of the \'jdbc\' in Java?', 'Java Database Connectivity', 'Java Data Connection', 'Java Data Control', 'None of the above', '0', 0, 'java'),
(52, 'What is the default scope of a bean in Spring?', 'Singleton', 'Prototype', 'Request', 'Session', '0', 0, 'java'),
(53, 'Which of the following is a NoSQL database?', 'MySQL', 'PostgreSQL', 'MongoDB', 'Oracle', '2', 0, 'java'),
(54, 'What is REST in web services?', 'Representational State Transfer', 'Remote State Transfer', 'Real-time State Transfer', 'None of the above', '0', 0, 'java'),
(55, 'What does the \'@RequestMapping\' annotation do in Spring?', 'Maps HTTP requests to handler methods', 'Defines a service', 'Creates a bean', 'None of the above', '0', 0, 'java'),
(56, 'What is the primary purpose of the Model-View-Controller (MVC) pattern?', 'Separation of concerns', 'Database management', 'Client-server architecture', 'None of the above', '0', 0, 'java'),
(57, 'Which of the following is a Java build tool?', 'Maven', 'Gradle', 'Ant', 'All of the above', '3', 0, 'java'),
(58, 'What is the function of \'application.properties\' in a Spring Boot application?', 'Configuration settings', 'Database settings', 'Environment variables', 'None of the above', '0', 0, 'java'),
(59, 'What is the purpose of the \'pom.xml\' file in Maven?', 'Project configuration', 'Dependency management', 'Build instructions', 'All of the above', '3', 0, 'java'),
(60, 'Which of the following is used to perform dependency injection in Spring?', '@Autowired', '@Inject', '@Component', 'All of the above', '3', 0, 'java'),
(61, 'What is the purpose of \'docker\' in full-stack development?', 'Containerization', 'Database management', 'Web server management', 'None of the above', '0', 0, 'java'),
(62, 'What is the primary language used for Android development?', 'Kotlin', 'Java', 'C++', 'Swift', '1', 0, 'java'),
(63, 'What is the purpose of \'JSON\' in web applications?', 'Data interchange format', 'Database management', 'Web server communication', 'None of the above', '0', 0, 'java'),
(64, 'Which of the following is a popular front-end framework?', 'Angular', 'Spring', 'Hibernate', 'Maven', '0', 0, 'java'),
(65, 'What is \'JPA\' used for in Java?', 'Java Persistence API', 'Java Process API', 'Java Performance API', 'None of the above', '0', 0, 'java'),
(66, 'What is the function of \'Spring Security\'?', 'Authentication and authorization', 'Data validation', 'Web scraping', 'None of the above', '0', 0, 'java'),
(67, 'Which of the following is an example of a relational database?', 'MySQL', 'MongoDB', 'Redis', 'Cassandra', '0', 0, 'java'),
(68, 'What is the purpose of \'CORS\' in web applications?', 'Cross-Origin Resource Sharing', 'Content-Object Resource Sharing', 'Cross-Origin Redirect Sharing', 'None of the above', '0', 0, 'java'),
(69, 'What is \'Spring Boot\' primarily used for?', 'Rapid application development', 'Database management', 'Web server configuration', 'None of the above', '0', 0, 'java'),
(70, 'What is the superclass of all classes in Java?', 'Object', 'Class', 'Main', 'String', '0', 0, 'java'),
(71, 'What is the purpose of the static keyword in Java?', 'To define a variable that belongs to the class', 'To define a method that can be called without creating an instance', 'To allocate memory for a variable at compile time', 'All of the above', '3', 0, 'java'),
(72, 'Which of the following is used to prevent a method from being overridden in Java?', 'static', 'final', 'abstract', 'private', '1', 0, 'java'),
(73, 'Which of the following is the correct way to declare an array in Java?', 'int arr[] = new int[5];', 'int arr = new int[5];', 'int[] arr = int[5];', 'array int arr = new int[5];', '0', 0, 'java');

-- CCNA 
INSERT INTO questions (id, correct_answers, is_multiple_choice, option1, option2, option3, option4, question, category) VALUES
(75, '1', 0, 'Forward packets within a local network', 'Route packets between different networks', 'Filter malicious traffic', 'Convert IP addresses to MAC addresses', 'What is the primary function of a router in a network?', 'ccna'),
(76, '1', 0, 'Layer 2', 'Layer 3', 'Layer 4', 'Layer 7', 'Which layer of the OSI model do routers primarily operate on?', 'ccna'),
(77, '1', 0, 'Layer 2 switches operate on IP addresses, Layer 3 switches operate on MAC addresses', 'Layer 2 switches operate on MAC addresses, Layer 3 switches operate on IP addresses', 'Layer 2 switches use VLANs, Layer 3 switches do not', 'Layer 3 switches are slower than Layer 2 switches', 'What is the primary difference between a Layer 2 and a Layer 3 switch?', 'ccna'),
(78, '1', 0, 'Switching only within VLANs', 'Routing between VLANs', 'ARP resolution', 'Firewall capabilities', 'Which of the following is a feature of Layer 3 switches?', 'ccna'),
(79, '1', 0, 'To forward packets between networks', 'To provide services to client devices', 'To route IP packets', 'To control switches', 'What is the primary function of a server in a network?', 'ccna'),
(80, '2', 0, 'Web hosting', 'Email hosting', 'Routing packets', 'Database management', 'Which of the following is NOT typically a role of a server?', 'ccna'),
(81, '1', 0, 'A device that provides network services', 'A device that initiates or receives network communication', 'A device that routes traffic', 'A wireless router', 'What is an endpoint in networking?', 'ccna'),
(82, '0', 0, 'Provides wireless signal coverage', 'Routes traffic between subnets', 'Converts analog signals to digital', 'Assigns IP addresses to clients', 'What does an access point do in a wireless network?', 'ccna'),
(83, '2', 0, '64 bits', '128 bits', '32 bits', '16 bits', 'What is the length of an IPv4 address?', 'ccna'),
(84, '1', 0, '16', '32', '64', '128', 'How many hexadecimal digits are there in an IPv6 address?', 'ccna'),
(85, '1', 0, 'Routing packets between different networks', 'Forwarding frames within a network based on MAC addresses', 'Translating domain names to IP addresses', 'Forwarding data based on IP addresses', 'What is switching in a network?', 'ccna'),
(86, '0', 0, 'Layer 2', 'Layer 3', 'Layer 4', 'Layer 5', 'In which layer of the OSI model does switching occur?', 'ccna'),
(87, '1', 0, 'Virtual Link Access Node', 'Virtual Local Area Network', 'Virtual Logical Access Network', 'Virtual Layer Access Node', 'What does VLAN stand for?', 'ccna'),
(88, '0', 0, 'To isolate network traffic within the same physical network', 'To route packets between networks', 'To manage wireless access points', 'To assign IP addresses to devices', 'What is the primary purpose of a VLAN?', 'ccna'),
(89, '1', 0, 'To route traffic between VLANs', 'To prevent loops in a network', 'To assign IP addresses', 'To improve wireless signal strength', 'What is the purpose of the Spanning Tree Protocol (STP)?', 'ccna'),
(90, '0', 0, 'Layer 2', 'Layer 3', 'Layer 4', 'Layer 7', 'STP operates at which OSI layer?', 'ccna'),
(91, '1', 0, 'Wide Local Area Network', 'Wireless Local Area Network', 'Wired Local Access Network', 'Wireless Layer Access Network', 'What does WLAN stand for?', 'ccna'),
(92, '0', 0, '2.4 GHz and 5 GHz', '1.2 GHz and 6 GHz', '3.1 GHz and 4.9 GHz', '7.2 GHz and 9 GHz', 'What frequency bands do WLANs typically operate on?', 'ccna'),
(93, '1', 0, 'MAC address', 'IP address', 'Domain name', 'URL', 'A router uses which of the following to make forwarding decisions?', 'ccna'),
(94, '2', 0, 'BGP', 'RIP', 'OSPF', 'SMTP', 'Which routing protocol is commonly used within autonomous systems?', 'ccna'),
(95, '1', 0, 'A route learned automatically by a router', 'A route manually configured by an administrator', 'A route used only for wireless traffic', 'A temporary route', 'What is a static route?', 'ccna'),
(96, '1', 0, 'It is not secure', 'It does not adapt to network changes', 'It is expensive', 'It requires IPv6', 'What is the primary disadvantage of static routing?', 'ccna'),
(97, '1', 0, 'A default route used by a router', 'A backup static route with a higher administrative distance', 'A dynamic route that adapts to changes', 'A temporary route used in wireless networks', 'What is a floating static route?', 'ccna'),
(98, '0', 0, 'When the primary route fails', 'When the network is congested', 'When a device sends a ping request', 'When the router is restarted', 'When does a floating static route become active?', 'ccna'),
(99, '1', 0, 'To assign IP addresses to devices', 'To forward packets to external networks', 'To resolve domain names', 'To provide encryption for wireless traffic', 'What is the function of a default gateway?', 'ccna'),
(100, '1', 0, 'To provide domain name resolution', 'To assign IP addresses automatically', 'To encrypt data traffic', 'To route packets between networks', 'What is the purpose of DHCP in a network?', 'ccna'),
(101, '3', 0, 'By subnet masks', 'By IP addresses', 'By MAC addresses', 'By logical segmentation', 'How is traffic separated in VLANs?', 'ccna'),
(102, '1', 0, 'VTP', '802.1Q', 'RIP', 'BGP', 'Which protocol is used to carry VLAN information over trunk links?', 'ccna'),
(103, '1', 0, 'Public IP address', 'Private IP address', 'Multicast address', 'Loopback address', 'What type of address is \'192.168.1.1\'?', 'ccna'),
(104, '2', 0, '32', '64', '128', '256', 'How many bits are there in an IPv6 address?', 'ccna'),
(105, '2', 0, 'IP address conflicts', 'VLAN segmentation', 'Broadcast storms', 'Domain name resolution issues', 'What does STP prevent in a switched network?', 'ccna'),
(106, '0', 0, 'Rapid STP (RSTP)', 'Basic STP', 'PortFast', 'Layer 3 STP', 'Which type of STP is most commonly used in modern networks?', 'ccna'),
(107, '3', 0, 'WEP', 'WPA', 'WPA2', 'WPA3', 'Which security protocol is considered the most secure for WLANs?', 'ccna'),
(108, '0', 0, 'Service Set Identifier', 'Security Signal Identification', 'Standard Signal Identification', 'Service Signal Identifier', 'What does SSID stand for in WLANs?', 'ccna'),
(109, '1', 0, 'OSPF', 'BGP', 'EIGRP', 'RIP', 'Which protocol is used to exchange routing information between different autonomous systems?', 'ccna'),
(110, '0', 0, 0, '1', '10', '20', 'What is the administrative distance of a directly connected route?', 'ccna'),
(111, '1', 0, 'A single VLAN used across multiple switches', 'A connection that carries multiple VLANs', 'A default VLAN used for management', 'A protocol for routing VLAN traffic', 'What is a VLAN trunk?', 'ccna'),
(112, '2', 0, '100', '256', '4096', '8192', 'What is the maximum number of VLANs supported on a switch?', 'ccna'),
(113, '0', 0, 'Application layer', 'Transport layer', 'Network layer', 'Data link layer', 'Which layer of the OSI model deals with encryption and compression?', 'ccna');

-- AWS
INSERT INTO questions (question, option1, option2, option3, option4, correct_answers, category, is_multiple_choice) VALUES
('1 or 0? Each AWS region is designed to be completely isolated from the other AWS regions', '1', '0', '', '', 0, 'aws', 0),
('1 or 0? Each region has a minimum number of 1 availability zones and the maximum is 4', '1', '0', '', '', 1, 'aws', 0),
('What considerations to take when choosing an AWS region for running a new application?', 'The region with most number of Availability Zones', 'The region closest to the AWS global headquarters', 'The region that minimizes latency for your users and complies with data residency regulations', 'The region with the cheapest EC2 pricing overall', 2, 'aws', 0),
('1 or 0? IAM configuration is defined globally and not per region', '1', '0', '', '', 0, 'aws', 0),
('1 or 0? When creating an AWS account, root account is created by default. This is the recommended account to use and share in your organization', '1', '0', '', '', 1, 'aws', 0),
('1 or 0? Groups in AWS IAM, can contain only users and no other groups', '1', '0', '', '', 0, 'aws', 0),
('1 or 0? Users in AWS IAM, can belong only to a single group', '1', '0', '', '', 1, 'aws', 0),
('What is AWS Identity and Access Management (IAM), and which of the following is a feature it provides?', 'It manages EC2 instance performance optimization', 'It provides a firewall to block malicious traffic', 'It allows you to manage access to AWS services and resources securely', 'It is used to automatically scale applications across regions', 2, 'aws', 0),
("1 or 0? If a user in AWS is using password for authenticating, he doesn't needs to enable MFA", '1', '0', '', '', 1, 'aws', 0),
('Which of the following best characterizes the purpose of an IAM Role in AWS?', 'A permanent identity assigned to users for long-term access to AWS services', 'A temporary set of permissions that can be assumed by trusted entities such as AWS services.', 'A mechanism for grouping IAM users under a common set of policies', 'A script used for provisioning access control lists to AWS resources', 1, 'aws', 0),
('In the context of AWS IAM, which of the following statements most accurately describes what a policy is?', 'A YAML-based document that controls access to AWS billing features', 'A configuration file attached to resources that defines their behavior', 'A JSON document that specifies who can assume an IAM role', 'A JSON-based permission document that defines what actions are allowed or denied on specific AWS resources', 3, 'aws', 0),
('A user is unable to access an s3 bucket. What might be the problem?', 'Move the S3 bucket to the user’s default region', 'Attach a policy to the user granting permissions to access the S3 bucket', 'Modify the bucket’s ACL to grant the user read permissions', 'Enable S3 Block Public Access settings on the bucket', 1, 'aws', 0),
('1 or 0? EC2 is a regional service', '1', '0', '', '', 0, 'aws', 0),
('1 or 0? AMI are built for specific region', '1', '0', '', '', 0, 'aws', 0),
('In the EC2 instance type name m5.large, what does each component represent?', 'M = Generation 5=Instance Class, Large=Storage Size', 'M = Memory Optimized, 5 = Burstable performance tier, Large = network throughput', 'M = Instance Class, 5 = Generation, Large = Size of the instance', 'M = Reserved Instance Type, 5 = core count, Large = EBS Volume size', 2, 'aws', 0),
('1 or 0? The following are instance types available for a user in AWS:', 'Compute optimized', 'Network optimized', 'Web Optimized', '', 2, 'aws', 0),
('What happens to EBS volumes when an EC2 instance is terminated?', 'All attached EBS volumes are deleted immediately by default.', 'By default, the root volume is deleted, but any additional EBS volumes persist unless specified otherwise.', 'By default, both the root and any additional EBS volumes are preserved.', 'All EBS volumes, including snapshots, are retained and billed until manually deleted.', 1, 'aws', 0),
('What happens to the attached EBS volumes when an EC2 instance is stopped (not terminated)?', 'All EBS volumes are deleted, including the root volume', 'The root volume is deleted, but data volumes remain intact', 'The EBS volumes are detached and archived to S3', 'The EBS volumes remain intact and will be available when the instance is started again', 3, 'aws', 0),
('1 or 0? EBS volumes are locked to a specific availability zone', '1', '0', '', '', 0, 'aws', 0),
('What are the use cases for using EBS snapshots?', 'Create a point-in-time copy of an EBS volume that can be used to create a new volume in a different Availability Zone or Region.', 'Immediately restore an EBS volume to a previous state without any downtime.', 'Provide a continuous, real-time backup of an EBS volume.', 'Directly replace a failed EBS volume with a snapshot without any data loss or service interruption.', 0, 'aws', 0),
('Under what condition can a single EBS volume be attached to multiple EC2 instances simultaneously?', 'When using Provisioned IOPS SSD (io1 or io2) volumes with Multi-Attach enabled', 'When using general purpose SSD (gp3) volumes', 'When using standard magnetic volumes', 'When launching instances in the same Availability Zone without IAM restrictions', 0, 'aws', 0),
('1 or 0? EBS is a network drive hence, it requires network connectivity', '1', '0', '', '', 0, 'aws', 0),
('1 or 0? EFS is locked into a single availability zone', '1', '0', '', '', 1, 'aws', 0),
('Which of the following are common use cases for using Amazon EFS (Elastic File System)?', 'Hosting container images and AMIs for reuse across Regions', 'Data sharing, web serving, and content management across multiple EC2 instances', 'Temporary high-speed block storage for individual EC2 instances', 'Object-level storage for static websites with global access', 1, 'aws', 0),
('1 or 0? EFS only compatible with Linux based AMI', '1', '0', '', '', 0, 'aws', 0),
("1 or 0? EFS requires the user to perform capacity planning as it doesn't scales automatically", '1', '0', '', '', 1, 'aws', 0),
('1 or 0? Reserved instance has to be used for a minimum of 1 year', '1', '0', '', '', 0, 'aws', 0),
('You need to launch an EC2 instance for a short-term project, and it is critical that the workload is not interrupted. Which EC2 pricing model is the most appropriate?', 'Reserved Instances', 'Spot Instances', 'On-Demand Instances', 'Savings Plans', 2, 'aws', 0),
('1 or 0? One security group can be attached to multiple instances', '1', '0', '', '', 0, 'aws', 0),
('1 or 0? Security groups are not locked down to a region and VPC', '1', '0', '', '', 1, 'aws', 0),
("In the context of AWS EC2, what does 'bootstrapping' refer to and how is it typically used?", 'Encrypting the EBS volumes before launching the instance', 'Creating a snapshot of the root volume before instance shutdown', 'Attaching IAM roles to an instance for temporary access credentials', 'Automatically configuring an instance at launch using user data scripts', 3, 'aws', 0),
("1 or 0? It's possible to have multiple VPCs in one region", '1', '0', '', '', 0, 'aws', 0),
('1 or 0? One or more VPCs can be attached to one Internet Gateway', '1', '0', '', '', 1, 'aws', 0),
('After restarting your EC2 instance, you notice that the public IP address has changed. How can you ensure the IP address remains the same across restarts?', 'Use an Elastic Load Balancer (ELB) in front of the instance', 'Stop using public IPs and switch to private IPs only', 'Assign an Elastic IP to the instance', 'Change the instance type to a reserved instance', 2, 'aws', 0),
("1 or 0? In AWS Lambda, you are charged as long as a function exists, regardless of whether it's running or not", '1', '0', '', '', 1, 'aws', 0),
('1 or 0? Basic lambda permissions allow you only to upload logs to Amazon CloudWatch Logs', '1', '0', '', '', 0, 'aws', 0),
('What must be done to make an EC2 instance part of an Amazon ECS (Elastic Container Service) cluster?', 'Attach an IAM role with read-only S3 permissions', 'Install the ECS agent and configure the instance to join the cluster', 'Enable auto-scaling on the EC2 instance', 'Convert the EC2 instance to a Lambda function', 1, 'aws', 0),
('What features suits CloudWatch operation?', 'CloudWatch does not support custom metrics', 'collect and monitor operating system and application generated log files', 'CloudTrail generates logs automatically when AWS account is activated', 'AWS services automatically create logs for CloudWatch', 1, 'aws', 0),
('What is required to ensure that new EC2 instances launched by an Auto Scaling Group are correctly configured?', 'Tagging the instances with a specific key', 'Creating a CloudFormation template', 'Defining a Launch Template', 'Enabling S3 bucket access on the instance', 2, 'aws', 0),
('What happens when an EC2 instance registered with an ELB through an ASG fails its health check?', 'ELB will reboot the instance automatically', 'The instance will be manually deregistered by AWS support', 'ELB will send an SNS alert but take no action', 'ASG will terminate the instance and launch a new one', 3, 'aws', 0),
('1 or 0? RDS read replicas are asynchronous?', '1', '0', '', '', 0, 'aws', 0),
('1 or 0? Amazon RDS supports MongoDB?', '1', '0', '', '', 1, 'aws', 0),
('What is the primary benefit of using RDS read replicas?', 'To enable automatic failover in case the primary database fails', 'To distribute read-heavy workloads and improve application performance', 'To reduce storage costs by compressing database files', 'To encrypt data at rest without performance impact', 1, 'aws', 0),
('1 or 0? Migrating AWS RDS from single AZ to multi AZ is an operation with downtime (meaning there is a need to stop the DB)', '1', '0', '', '', 1, 'aws', 0),
('What is the main difference between a CNAME record and an Alias record in AWS Route 53?', 'CNAME records can only point to IP addresses, while Alias records can only point to domain names', 'Alias records are slower to resolve than CNAME records', 'CNAME records provide better security than Alias records', 'CNAME is used for mapping one hostname to any other hostname while Alias is used to map an hostname to an AWS resource.', 3, 'aws', 0),
('Suppose you need to route % of your traffic to Instance A and % of your traffic to Instance B. Which Route 53 routing policy would you choose?', 'Simple Routing Policy', 'Latency-based Routing Policy', 'Weighted Routing Policy', 'Geolocation Routing Policy', 2, 'aws', 0),
('You need persistent shared storage between your containers where some are running in Fargate and some in ECS EC2. The storage should be accessible across multiple Availability Zones. What would you use?', 'Amazon EBS volumes', 'Docker local volumes', 'Amazon S3 buckets', 'Amazon EFS file system', 3, 'aws', 0);
