-- java questions
INSERT INTO questions (question, option1, option2, option3, option4, correct_answers, is_multiple_choice, category) VALUES
('How many pillars of OOPs java has?', '3', '4', '5', '6', '2', 0, 'java'),
( 'What is the default value of a boolean variable in Java?', '1', '0', 'Null', '0', '2', 0, 'java'),
( 'Which of the following is not a valid data type in Java?', 'int', 'float', 'double', 'real', '3', 0, 'java'),
( 'What is the main purpose of the final keyword in Java?', 'To declare a constant', 'To prevent method overriding', 'To prevent inheritance', 'All of the above', '3', 0, 'java'),
( 'Which of the following methods can be used to start a thread in Java?', 'run()', 'start()', 'execute()', 'begin()', '1', 0, 'java'),
( 'Output: int x = 10; int y = 20; System.out.println(x + y + "10");', '3010', '2010', '30', '210', '0', 0, 'java'),
( 'What is the main entry point of a Java application?', 'main()', 'start()', 'init()', 'run()', '0', 0, 'java'),
( 'Which keyword is used to create a class in Java?', 'class', 'create', 'new', 'define', '0', 0, 'java'),
( 'Which of the following are primitive data types in Java?', 'int', 'String', 'boolean', 'char', '0,2,3', 1, 'java'),
( 'Which of the following are valid keywords in Java?', 'static', 'void', 'main', 'function', '0,1,2', 1, 'java'),
( 'Which of the following are valid ways to create an object in Java?', 'Using new keyword', 'Using factory methods', 'Using cloning', 'Using constructors', '0,1,3', 1, 'java'),
( 'Which of the following can be used to handle exceptions in Java?', 'try-catch', 'throw', 'throws', 'finally', '0,1,2,3', 1, 'java'),
( 'Which of the following are features of Java?', 'Platform independence', 'Object-oriented', 'Automatic garbage collection', 'Pointer arithmetic', '0,1,2', 1, 'java'),
( 'Which of the following are types of loops in Java?', 'for', 'while', 'do-while', 'foreach', '0,1,2,3', 1, 'java'),
( 'Which of the following are collection interfaces in Java?', 'List', 'Set', 'Map', 'Array', '0,1,2', 1, 'java'),
( 'Which of the following access modifiers are available in Java?', 'public', 'private', 'protected', 'friend', '0,1,2', 1, 'java'),
( 'Which of the following are valid ways to declare an array in Java?', 'int[] arr;', 'int arr[];', 'int arr = new int[5];', 'int[] arr = new int[];', '0,1,2', 1, 'java'),
('Which of the following statements about interfaces are 1?', 'Interfaces can extend other interfaces', 'An interface can contain method implementations', 'A class can implement multiple interfaces', 'Interfaces cannot have instance variables', '0,2,3', 1, 'java'),
( 'Which of the following are valid Java annotations?', '@Override', '@Entity', '@Service', '@Main', '0,1,2', 1, 'java'),
( 'Which of the following are valid ways to implement a thread in Java?', 'Extending Thread class', 'Implementing Runnable interface', 'Using ExecutorService', 'Creating a method', '0,1,2', 1, 'java'),
( 'Which of the following statements about the Java Collections Framework are 1?', 'It provides data structures for storing groups of objects', 'It supports sorting and searching operations', 'All collections implement the Collection interface', 'Collections can be synchronized', '0,1,2,3', 1, 'java'),
( 'Which of the following are valid Java stream operations?', 'filter()', 'map()', 'reduce()', 'collect()', '0,1,2,3', 1, 'java'),
( 'Which of the following are commonly used Java frameworks?', 'Spring', 'Hibernate', 'JSF', 'Angular', '0,1,2', 1, 'java'),
('Which of the following statements about Java inheritance are 1?', 'Java supports multiple inheritance', 'A class can only extend one class', 'Subclasses can override methods of superclasses', 'Constructors are inherited', '1,2', 1, 'java'),
( 'Which of the following are valid types of exceptions in Java?', 'Checked exceptions', 'Unchecked exceptions', 'Errors', 'Runtime exceptions', '0,1,2,3', 1, 'java'),
('Which of the following statements about Java memory management are 1?', 'Memory allocation is done at runtime', 'Garbage collector automatically deallocates memory', 'Memory leaks can occur', 'Finalizers can be used to clean up resources', '0,1,2,3', 1, 'java'),
( 'Which of the following are types of Java applications?', 'Standalone applications', 'Web applications', 'Mobile applications', 'Console applications', '0,1,2,3', 1, 'java'),
( 'What does JVM stand for?', 'Java Variable Machine', 'Java Virtual Machine', 'Java Visual Machine', 'Java Value Machine', '1', 0, 'java'),
( 'Which of the following is a valid way to declare an array in Java?', 'int[] arr;', 'int arr[];', 'Both 1 and 2', 'None of the above', '2', 0, 'java'),
('What is the default value of a boolean in Java?', '1', '0', '0', '1', '1', 0, 'java'),
('Which of the following is not a valid access modifier in Java?', 'public', 'protected', 'private', 'internal', '3', 0, 'java'),
('What does the \'static\' keyword indicate in Java?', 'Instance variable', 'Class variable', 'Local variable', 'Global variable', '1', 0, 'java'),
('Which of the following can throw an exception in Java?', 'Runtime', 'Checked', 'Unchecked', 'All of the above', '3', 0, 'java'),
('What is the purpose of the \'this\' keyword in Java?', 'To refer to the current instance', 'To call a constructor', 'To access static members', 'None of the above', '0', 0, 'java'),
('Which method is used to compare two strings in Java?', 'compare()', 'equals()', '==', 'compareTo()', '1', 0, 'java'),
('What is the output of \'System.out.println(1 + 2 + "3");\'?', '33', '6', '15', 'Error', '1', 0, 'java'),
('Which of the following is a valid constructor in Java?', 'ClassName()', 'void ClassName()', 'ClassName;', 'new ClassName()', '0', 0, 'java'),
('What does the \'final\' keyword do in Java?', 'Makes a variable constant', 'Prevents method overriding', 'Prevents inheritance', 'All of the above', '3', 0, 'java'),
('What is the size of an int in Java?', '2 bytes', '4 bytes', '8 bytes', '16 bytes', '1', 0, 'java'),
('Which of the following collections is ordered in Java?', 'HashSet', 'TreeSet', 'ArrayList', 'HashMap', '2', 0, 'java'),
('What is a Java package?', 'A collection of classes', 'A way to organize classes', 'Both 1 and 2', 'None of the above', '2', 0, 'java'),
('Which of the following is used to create a thread in Java?', 'Runnable', 'Thread', 'Both 1 and 2', 'Process', '2', 0, 'java'),
('What does the \'super\' keyword do in Java?', 'Access parent class methods', 'Call a superclass constructor', 'Both 1 and 2', 'None of the above', '2', 0, 'java'),
('Which annotation is used to mark a method as an override in Java?', '@Override', '@OverrideMethod', '@OverrideFunc', '@Super', '0', 0, 'java'),
('What does the term \'polymorphism\' refer to in Java?', 'Multiple forms of methods', 'Overloading methods', 'Overriding methods', 'All of the above', '3', 0, 'java'),
('What is a lambda expression in Java?', 'A way to define anonymous functions', 'A new data type', 'An exception', 'None of the above', '0', 0, 'java'),
('Which of the following is not a primitive data type in Java?', 'int', 'float', 'String', 'boolean', '2', 0, 'java'),
('What is the main purpose of the \'try-catch\' block in Java?', 'To handle exceptions', 'To define a loop', 'To create threads', 'None of the above', '0', 0, 'java'),
('Which of the following interfaces allows you to iterate over a collection in Java?', 'Iterable', 'Collection', 'Iterator', 'All of the above', '3', 0, 'java'),
('Which framework is commonly used for building web applications in Java?', 'Spring', 'Hibernate', 'Struts', 'All of the above', '3', 0, 'java'),
('What is the purpose of the \'jdbc\' in Java?', 'Java Database Connectivity', 'Java Data Connection', 'Java Data Control', 'None of the above', '0', 0, 'java'),
('What is the default scope of a bean in Spring?', 'Singleton', 'Prototype', 'Request', 'Session', '0', 0, 'java'),
('Which of the following is a NoSQL database?', 'MySQL', 'PostgreSQL', 'MongoDB', 'Oracle', '2', 0, 'java'),
('What is REST in web services?', 'Representational State Transfer', 'Remote State Transfer', 'Real-time State Transfer', 'None of the above', '0', 0, 'java'),
( 'What does the \'@RequestMapping\' annotation do in Spring?', 'Maps HTTP requests to handler methods', 'Defines a service', 'Creates a bean', 'None of the above', '0', 0, 'java'),
( 'What is the primary purpose of the Model-View-Controller (MVC) pattern?', 'Separation of concerns', 'Database management', 'Client-server architecture', 'None of the above', '0', 0, 'java'),
( 'Which of the following is a Java build tool?', 'Maven', 'Gradle', 'Ant', 'All of the above', '3', 0, 'java'),
('What is the function of \'application.properties\' in a Spring Boot application?', 'Configuration settings', 'Database settings', 'Environment variables', 'None of the above', '0', 0, 'java'),
('What is the purpose of the \'pom.xml\' file in Maven?', 'Project configuration', 'Dependency management', 'Build instructions', 'All of the above', '3', 0, 'java'),
('Which of the following is used to perform dependency injection in Spring?', '@Autowired', '@Inject', '@Component', 'All of the above', '3', 0, 'java'),
('What is the purpose of \'docker\' in full-stack development?', 'Containerization', 'Database management', 'Web server management', 'None of the above', '0', 0, 'java'),
('What is the primary language used for Android development?', 'Kotlin', 'Java', 'C++', 'Swift', '1', 0, 'java'),
('What is the purpose of \'JSON\' in web applications?', 'Data interchange format', 'Database management', 'Web server communication', 'None of the above', '0', 0, 'java'),
('Which of the following is a popular front-end framework?', 'Angular', 'Spring', 'Hibernate', 'Maven', '0', 0, 'java'),
('What is \'JPA\' used for in Java?', 'Java Persistence API', 'Java Process API', 'Java Performance API', 'None of the above', '0', 0, 'java'),
('What is the function of \'Spring Security\'?', 'Authentication and authorization', 'Data validation', 'Web scraping', 'None of the above', '0', 0, 'java'),
('Which of the following is an example of a relational database?', 'MySQL', 'MongoDB', 'Redis', 'Cassandra', '0', 0, 'java'),
('What is the purpose of \'CORS\' in web applications?', 'Cross-Origin Resource Sharing', 'Content-Object Resource Sharing', 'Cross-Origin Redirect Sharing', 'None of the above', '0', 0, 'java'),
('What is \'Spring Boot\' primarily used for?', 'Rapid application development', 'Database management', 'Web server configuration', 'None of the above', '0', 0, 'java'),
('What is the superclass of all classes in Java?', 'Object', 'Class', 'Main', 'String', '0', 0, 'java'),
('What is the purpose of the static keyword in Java?', 'To define a variable that belongs to the class', 'To define a method that can be called without creating an instance', 'To allocate memory for a variable at compile time', 'All of the above', '3', 0, 'java'),
('Which of the following is used to prevent a method from being overridden in Java?', 'static', 'final', 'abstract', 'private', '1', 0, 'java'),
('Which of the following is the correct way to declare an array in Java?', 'int arr[] = new int[5];', 'int arr = new int[5];', 'int[] arr = int[5];', 'array int arr = new int[5];', '0', 0, 'java');

-- CCNA 
INSERT INTO questions (correct_answers, is_multiple_choice, option1, option2, option3, option4, question, category) VALUES
( 1, 0, 'Forward packets within a local network', 'Route packets between different networks', 'Filter malicious traffic', 'Convert IP addresses to MAC addresses', 'What is the primary function of a router in a network?', 'ccna'),
( 1, 0, 'Layer 2', 'Layer 3', 'Layer 4', 'Layer 7', 'Which layer of the OSI model do routers primarily operate on?', 'ccna'),
( 1, 0, 'Layer 2 switches operate on IP addresses, Layer 3 switches operate on MAC addresses', 'Layer 2 switches operate on MAC addresses, Layer 3 switches operate on IP addresses', 'Layer 2 switches use VLANs, Layer 3 switches do not', 'Layer 3 switches are slower than Layer 2 switches', 'What is the primary difference between a Layer 2 and a Layer 3 switch?', 'ccna'),
( 1, 0, 'Switching only within VLANs', 'Routing between VLANs', 'ARP resolution', 'Firewall capabilities', 'Which of the following is a feature of Layer 3 switches?', 'ccna'),
( 1, 0, 'To forward packets between networks', 'To provide services to client devices', 'To route IP packets', 'To control switches', 'What is the primary function of a server in a network?', 'ccna'),
( 2, 0, 'Web hosting', 'Email hosting', 'Routing packets', 'Database management', 'Which of the following is NOT typically a role of a server?', 'ccna'),
( 1, 0, 'A device that provides network services', 'A device that initiates or receives network communication', 'A device that routes traffic', 'A wireless router', 'What is an endpoint in networking?', 'ccna'),
( 0, 0, 'Provides wireless signal coverage', 'Routes traffic between subnets', 'Converts analog signals to digital', 'Assigns IP addresses to clients', 'What does an access point do in a wireless network?', 'ccna'),
( 2, 0, '64 bits', '128 bits', '32 bits', '16 bits', 'What is the length of an IPv4 address?', 'ccna'),
( 1, 0, '16', '32', '64', '128', 'How many hexadecimal digits are there in an IPv6 address?', 'ccna'),
( 1, 0, 'Routing packets between different networks', 'Forwarding frames within a network based on MAC addresses', 'Translating domain names to IP addresses', 'Forwarding data based on IP addresses', 'What is switching in a network?', 'ccna'),
( 0, 0, 'Layer 2', 'Layer 3', 'Layer 4', 'Layer 5', 'In which layer of the OSI model does switching occur?', 'ccna'),
( 1, 0, 'Virtual Link Access Node', 'Virtual Local Area Network', 'Virtual Logical Access Network', 'Virtual Layer Access Node', 'What does VLAN stand for?', 'ccna'),
( 0, 0, 'To isolate network traffic within the same physical network', 'To route packets between networks', 'To manage wireless access points', 'To assign IP addresses to devices', 'What is the primary purpose of a VLAN?', 'ccna'),
( 1, 0, 'To route traffic between VLANs', 'To prevent loops in a network', 'To assign IP addresses', 'To improve wireless signal strength', 'What is the purpose of the Spanning Tree Protocol (STP)?', 'ccna'),
( 0, 0, 'Layer 2', 'Layer 3', 'Layer 4', 'Layer 7', 'STP operates at which OSI layer?', 'ccna'),
( 1, 0, 'Wide Local Area Network', 'Wireless Local Area Network', 'Wired Local Access Network', 'Wireless Layer Access Network', 'What does WLAN stand for?', 'ccna'),
( 0, 0, '2.4 GHz and 5 GHz', '1.2 GHz and 6 GHz', '3.1 GHz and 4.9 GHz', '7.2 GHz and 9 GHz', 'What frequency bands do WLANs typically operate on?', 'ccna'),
( 1, 0, 'MAC address', 'IP address', 'Domain name', 'URL', 'A router uses which of the following to make forwarding decisions?', 'ccna'),
( 2, 0, 'BGP', 'RIP', 'OSPF', 'SMTP', 'Which routing protocol is commonly used within autonomous systems?', 'ccna'),
( 1, 0, 'A route learned automatically by a router', 'A route manually configured by an administrator', 'A route used only for wireless traffic', 'A temporary route', 'What is a static route?', 'ccna'),
( 1, 0, 'It is not secure', 'It does not adapt to network changes', 'It is expensive', 'It requires IPv6', 'What is the primary disadvantage of static routing?', 'ccna'),
( 1, 0, 'A default route used by a router', 'A backup static route with a higher administrative distance', 'A dynamic route that adapts to changes', 'A temporary route used in wireless networks', 'What is a floating static route?', 'ccna'),
( 0, 0, 'When the primary route fails', 'When the network is congested', 'When a device sends a ping request', 'When the router is restarted', 'When does a floating static route become active?', 'ccna'),
( 1, 0, 'To assign IP addresses to devices', 'To forward packets to external networks', 'To resolve domain names', 'To provide encryption for wireless traffic', 'What is the function of a default gateway?', 'ccna'),
( 1, 0, 'To provide domain name resolution', 'To assign IP addresses automatically', 'To encrypt data traffic', 'To route packets between networks', 'What is the purpose of DHCP in a network?', 'ccna'),
( 3, 0, 'By subnet masks', 'By IP addresses', 'By MAC addresses', 'By logical segmentation', 'How is traffic separated in VLANs?', 'ccna'),
( 1, 0, 'VTP', '802.1Q', 'RIP', 'BGP', 'Which protocol is used to carry VLAN information over trunk links?', 'ccna'),
( 1, 0, 'Public IP address', 'Private IP address', 'Multicast address', 'Loopback address', 'What type of address is \'192.168.1.1\'?', 'ccna'),
( 2, 0, '32', '64', '128', '256', 'How many bits are there in an IPv6 address?', 'ccna'),
(2, 0, 'IP address conflicts', 'VLAN segmentation', 'Broadcast storms', 'Domain name resolution issues', 'What does STP prevent in a switched network?', 'ccna'),
(0, 0, 'Rapid STP (RSTP)', 'Basic STP', 'PortFast', 'Layer 3 STP', 'Which type of STP is most commonly used in modern networks?', 'ccna'),
( 3, 0, 'WEP', 'WPA', 'WPA2', 'WPA3', 'Which security protocol is considered the most secure for WLANs?', 'ccna'),
( 0, 0, 'Service Set Identifier', 'Security Signal Identification', 'Standard Signal Identification', 'Service Signal Identifier', 'What does SSID stand for in WLANs?', 'ccna'),
( 1, 0, 'OSPF', 'BGP', 'EIGRP', 'RIP', 'Which protocol is used to exchange routing information between different autonomous systems?', 'ccna'),
( 0, 0, 0, '1', '10', '20', 'What is the administrative distance of a directly connected route?', 'ccna'),
( 1, 0, 'A single VLAN used across multiple switches', 'A connection that carries multiple VLANs', 'A default VLAN used for management', 'A protocol for routing VLAN traffic', 'What is a VLAN trunk?', 'ccna'),
(2, 0, '100', '256', '4096', '8192', 'What is the maximum number of VLANs supported on a switch?', 'ccna'),
(0, 0, 'Application layer', 'Transport layer', 'Network layer', 'Data link layer', 'Which layer of the OSI model deals with encryption and compression?', 'ccna');

-- Networking part-1
INSERT INTO questions (question, option1, option2, option3, option4, correct_answers, category, is_multiple_choice) VALUES
('Which of the following transmission directions listed is not a legitimate channel?', 'Simplex', 'Half Duplex', 'Full Duplex', 'Double Duplex', 3, 'networking', 0),
('The location of a resource on the internet is given by its?', 'Protocol', 'URL', 'E-mail address', 'ICQ', 1, 'networking', 0),
('Communication between a computer and a keyboard involves transmission?', 'simplex', 'half-duplex', 'full-duplex', 'automatic', 0, 'networking', 0),
('A computer network permits sharing of?', 'Resources', 'Information', 'Both a & b', 'None of these', 2, 'networking', 0),
('Transmission mode controls the direction of signal flow.', 'True', 'False', '', '', 0, 'networking', 0),
('A transmission mode that can transmit data in both the directions but transmits in only one direction at a time.', 'simplex', 'half duplex', 'full duplex', 'semi-duplex', 1, 'networking', 0),
('Telephone networks operate in this mode.', 'simplex', 'half duplex', 'full duplex', 'semi-duplex', 1, 'networking', 0),
('A walkie-talkie operates in ____________.', 'simplex', 'half duplex', 'full duplex', 'semi-duplex', 1, 'networking', 0),
('The performance of data communications network depends on ..............', 'Number of users', 'The hardware and software', 'The transmission', 'All of the above', 3, 'networking', 0),
('OSI stands for __________', 'open system interconnection', 'operating system interface', 'optical service implementation', 'open service Internet', 0, 'networking', 0),
('The number of layers in ISO OSI reference model is __________', '4', '5', '6', '7', 3, 'networking', 0),
('TCP/IP model does not have ______ layer but OSI model have this layer.', 'session layer', 'transport layer', 'application layer', 'network layer', 0, 'networking', 0),
('Which layer is used to link the network support layers and user support layers?', 'session layer', 'data link layer', 'transport layer', 'network layer', 2, 'networking', 0),
('Which address is used on the internet for employing the TCP/IP protocols?', 'physical address and logical address', 'port address', 'specific address', 'all of the mentioned', 3, 'networking', 0),
('Which layer is responsible for process-to-process delivery in a general network model?', 'network layer', 'transport layer', 'session layer', 'data link layer', 1, 'networking', 0),
('Which layer provides the services to user?', 'application layer', 'session layer', 'presentation layer', 'physical layer', 0, 'networking', 0),
('Transmission data rate is decided by ____________', 'network layer', 'physical layer', 'data link layer', 'transport layer', 1, 'networking', 0),
('The physical layer is concerned with ___________', 'bit-by-bit delivery', 'process to process delivery', 'application to application delivery', 'port to port delivery', 0, 'networking', 0);

-- Networking part-2 
INSERT INTO questions (question, option1, option2, option3, option4, correct_answers, category, is_multiple_choice) VALUES
('Which transmission media provides the highest transmission speed in a network?', 'coaxial cable', 'twisted pair cable', 'optical fiber', 'electrical cable', 2, 'networking', 0),
('The physical layer translates logical communication requests from the ______ into hardware specific operations.', 'data link layer', 'network layer', 'transport layer', 'application layer', 0, 'networking', 0),
('The data link layer takes the packets from _________ and encapsulates them into frames for transmission.', 'network layer', 'physical layer', 'transport layer', 'application layer', 0, 'networking', 0),
('Which of the following tasks is not done by data link layer?', 'framing', 'error control', 'flow control', 'channel coding', 3, 'networking', 0),
('Header of a frame generally contains ______________', 'synchronization bytes', 'addresses', 'frame identifier', 'all of the mentioned', 3, 'networking', 0),
('Which of the following is the multiple access protocol for channel access control?', 'CSMA/CD', 'CSMA/CA', 'Both CSMA/CD & CSMA/CA', 'HDLC', 2, 'networking', 0),
('The network layer is concerned with __________ of data.', 'bits', 'frames', 'packets', 'bytes', 2, 'networking', 0),
('Which one of the following is not a function of network layer?', 'routing', 'inter-networking', 'congestion control', 'error control', 3, 'networking', 0),
('The network layer protocol for internet is __________', 'ethernet', 'internet protocol', 'hypertext transfer protocol', 'file transfer protocol', 1, 'networking', 0),
('Which of the following are transport layer protocols used in networking?', 'TCP and FTP', 'UDP and HTTP', 'TCP and UDP', 'HTTP and FTP', 2, 'networking', 0),
('Transmission control protocol ___________', 'is a connection-oriented protocol', 'uses a three-way handshake to establish a connection', 'receives data from application as a single stream', 'all of the mentioned', 3, 'networking', 0),
('You want to implement a mechanism that automates the IP configuration, including IP address, subnet mask, default gateway, and DNS information. Which protocol will you use to accomplish this?', 'SMTP', 'SNMP', 'DHCP', 'ARP', 2, 'networking', 0),
('TCP/IP is related to __________', 'ARPANET', 'OSI', 'DECNET', 'ALOHA', 0, 'networking', 0),
('TCP/IP layer is equivalent to combined Session, Presentation and _________', 'Network layer', 'Application layer', 'Transport layer', 'Physical layer', 1, 'networking', 0),
('A device operating at network layer is called __________', 'Router', 'Equalizer', 'Bridge', 'Repeater', 0, 'networking', 0),
('A packet in Transmission Control Protocol (TCP) is called a ____________', 'Transmittable slots', 'Packet', 'Segment', 'Source Slots', 2, 'networking', 0),
('An IP packet is called a ____________. ', 'user datagram', 'segment', 'datagram', 'none of the above', 2, 'networking', 0),
('A TCP packet is called a _____________.', 'user datagram', 'segment', 'datagram', 'none of the above', 1, 'networking', 0),
('The hardware address is called ____________', 'IP address', 'MAC address', 'Internet address', 'Network address', 1, 'networking', 0),
('The server should have a dedicated computer to perform the following operation ______________', 'Serving files', 'Processing requests', 'Storing data', 'All of the mentioned', 3, 'networking', 0),
('The combination of hardware and software that helps to manage the network is called ___________', 'Network operating system', 'Client server', 'Network protocol', 'Router', 0, 'networking', 0),
('Which of the following is not a type of a computer network?', 'LAN', 'MAN', 'WAN', 'DAN', 3, 'networking', 0),
('The main purpose of a computer network is ____________.', 'Resource sharing', 'Cost reduction', 'Efficiency improvement', 'All of the above', 3, 'networking', 0),
('Which of the following is a disadvantage of a network?', 'Maintenance costs', 'Security issues', 'All of the above', 'None of the above', 2, 'networking', 0),
('Which one of the following network topologies is least expensive to implement?', 'Star', 'Ring', 'Bus', 'Mesh', 2, 'networking', 0),
('A network device that forwards data packets between computer networks is called ____________.', 'Router', 'Switch', 'Hub', 'Modem', 0, 'networking', 0),
('In networking, which device regenerates the signal and sends it to other networks?', 'Router', 'Switch', 'Hub', 'Repeater', 3, 'networking', 0),
('Which of the following topology is the most difficult to install and configure?', 'Bus', 'Star', 'Mesh', 'Ring', 2, 'networking', 0),
('The number of nodes in a mesh topology is __________.', '3 or more', '4 or more', '5 or more', '2 or more', 0, 'networking', 0),
('Which of the following is an advantage of a mesh topology?', 'Redundancy', 'Easy installation', 'Low cost', 'None of these', 0, 'networking', 0),
('In a star topology, the failure of the central hub __________.', 'Will not affect the whole network', 'Will affect the whole network', 'Will affect only one node', 'None of these', 1, 'networking', 0),
('Which of the following is a disadvantage of a star topology?', 'Centralized control', 'Failure of the hub', 'Cost', 'All of the above', 3, 'networking', 0);

-- networking part-3
INSERT INTO questions (question, option1, option2, option3, option4, correct_answers, category, is_multiple_choice) VALUES
('In a ring topology, if one node fails __________.', 'The network will continue to function', 'The network will be affected', 'Only that node will be affected', 'None of these', 1, 'networking', 0),
('The transmission medium which can carry more data is __________.', 'Twisted pair', 'Coaxial cable', 'Optical fiber', 'All of these', 2, 'networking', 0),
('The protocol which is used to send e-mail is __________.', 'SMTP', 'FTP', 'HTTP', 'SNMP', 0, 'networking', 0),
('HTTP stands for __________.', 'Hypertext Transfer Protocol', 'Hyper Transfer Text Protocol', 'Hypertext Transmission Protocol', 'Hyper Transfer Transmission Protocol', 0, 'networking', 0),
('Which of the following is an example of a connection-oriented protocol?', 'UDP', 'IP', 'TCP', 'HTTP', 2, 'networking', 0),
('A unique address assigned to each device on a network is known as __________.', 'IP address', 'MAC address', 'Port address', 'Network address', 1, 'networking', 0),
('Which of the following is a standard for Ethernet networks?', '802.3', '802.11', '802.15', '802.16', 0, 'networking', 0),
('A device that connects multiple devices in a network and forwards data packets to the destination device is called __________.', 'Router', 'Switch', 'Hub', 'Bridge', 1, 'networking', 0),
('The basic unit of data in a computer network is __________.', 'Bit', 'Byte', 'Packet', 'Frame', 2, 'networking', 0),
('The main function of a switch is __________.', 'To connect devices', 'To filter traffic', 'To manage bandwidth', 'All of the above', 3, 'networking', 0),
('What type of cable is most commonly used in local area networks (LANs)?', 'Coaxial', 'Twisted pair', 'Fiber optic', 'None of the above', 1, 'networking', 0),
('In the client-server model, what is the main function of a server?', 'To request services from other computers', 'To provide resources and services to clients', 'To act as a user interface', 'To establish peer-to-peer connections', 1, 'networking', 0),
('Which of the following is an example of a client in the client-server model?', 'Database', 'Web browser', 'Router', 'Firewall', 1, 'networking', 0),
('What protocol is primarily used by web browsers and web servers in a client-server interaction?', 'FTP', 'SMTP', 'HTTP', 'SSH', 2, 'networking', 0),
('In a client-server model, which component initiates communication?', 'Server', 'Client', 'Router', 'Switch', 1, 'networking', 0),
('Which of the following is a disadvantage of the client-server model?', 'It is scalable and secure.', 'Centralized management of resources.', 'The server can become a bottleneck if overloaded.', 'It allows direct communication between clients without a server.', 2, 'networking', 0),
('What is a major advantage of the client-server model over the peer-to-peer model?', 'It offers decentralized control.', 'It allows for easier resource management and security.', 'It has less reliance on a central server.', 'It requires less infrastructure.', 1, 'networking', 0),
('Which of the following is NOT a characteristic of the client-server model?', 'Centralized server providing services', 'Clients request resources', 'Peer-to-peer communication between clients', 'Servers manage data and security', 2, 'networking', 0),
('Which of the following uses the client-server model to transfer files between a client and a server?', 'SSH', 'FTP', 'POP3', 'HTTP', 1, 'networking', 0),
('In the client-server model, where are databases typically hosted?', 'On the client side', 'On the server side', 'On both the client and server sides', 'In the cloud only', 1, 'networking', 0),
('What happens if the server in a client-server network goes down?', 'Clients can continue communicating with each other.', 'Clients can still access the server’s resources.', 'The entire network may become unavailable.', 'The server automatically switches to peer-to-peer mode.', 2, 'networking', 0),
('Which protocol is used to securely transfer web pages from a server to a client?', 'HTTP', 'HTTPS', 'FTP', 'Telnet', 1, 'networking', 0),
('Which of the following is a client-server database management system?', 'Oracle', 'Bluetooth', 'TCP', 'HTTP', 0, 'networking', 0),
('Which of the following cables is commonly used in Ethernet networks?', 'Coaxial cable', 'Fiber optic cable', 'Twisted pair cable', 'HDMI cable', 2, 'networking', 0),
('What is the maximum recommended length for a single Cat 5e Ethernet cable?', '10 meters', '50 meters', '100 meters', '500 meters', 2, 'networking', 0),
('Which type of cable is immune to electromagnetic interference (EMI)?', 'Coaxial cable', 'Fiber optic cable', 'Shielded twisted pair (STP) cable', 'Unshielded twisted pair (UTP) cable', 1, 'networking', 0),
('Which of the following cables uses light to transmit data?', 'Cat 6 cable', 'Fiber optic cable', 'Coaxial cable', 'Twisted pair cable', 1, 'networking', 0);

-- Linux Questions
INSERT INTO questions (question, option1, option2, option3, option4, correct_answers, category, is_multiple_choice) VALUES
("Which command is commonly used to display all mounted file systems and their respective usage in Linux?", "lsblk", "ls -ltr", "df -Th", "free -m", 2, "linux", 0),
("What is the primary purpose of the /etc/fstab file in Linux?", "It stores system wide environment variables and startup scripts", "It lists the available filesystem and their associated options for mounting at boot time", "It contains configurations settings for network interfaces and routing tables", "It stores user account information, including username and passwords", 1, "linux", 0),
("To grant Davis (and only Davis) full access to John's home directory, which command would you use without losing John's access?", "chmod 777 /home/john", "setfacl -m u:davis:rwx /home/john", "chown davis:davis /home/john", NULL, 1, "linux", 0),
("Which command is used to rollback package changes made with yum in CentOS or Red Hat Enterprise Linux?", "yum undo", "yum rollback", "yum history undo", "yum revert", 2, "linux", 0),
("Which of the following describes the purpose of the SUID (Set User ID) permission in Linux?", "It allows all the users to execute a file with the permission of the file's owner", "It enables a user to modify a file's content without changing its ownership", "It grants temporary superuser privilege to execute specific files with elevated permissions", "It restricts access to certain files based on user groups", 0, "linux", 0),
("Which file should you modify to host an application locally on your computer?", "/etc/hosts", "/etc/fstab", "/etc/apache2/sites-available/000-default.conf", "/etc/network/interfaces", 0, "linux", 0),
("What is the difference between sending signal 15 (SIGTERM) and signal 9 (SIGKILL) to a process in Linux?", "SIGTERM allows the process to perform cleanup operations before terminating, while SIGKILL forces the process to terminate immediately without any cleanup.", "SIGTERM forces the process to terminate immediately without any cleanup, while SIGKILL allows the process to perform cleanup operations before terminating.", "Both SIGTERM and SIGKILL allow the process to perform cleanup operations before terminating.", "Both SIGTERM and SIGKILL force the process to terminate immediately without any cleanup.", 0, "linux", 0),
("Which of the following statements best describes the purpose of the lsblk command in Linux?", "The lsblk command is used to display information about block devices, including their sizes, mount points, and types.", "The lsblk command is used to format disk partitions with a specific file system.", "The lsblk command is used to monitor system performance and resource usage.", "The lsblk command is used to manage user accounts and permissions.", 0, "linux", 0),
("Which command is used to check network activity (both incoming and outgoing connections) of a service in Linux?", "netstat -tuln", "ifconfig", "lsblk", "top", 0, "linux", 0),
("What is the name of the Linux kernel file?", "boot.kernel", "linux.bin", "vmlinuz", "kernel.img", 2, "linux", 0),
("Which of the following tools is specifically designed to provide real-time information about system processes and resource usage in Linux?", "ps", "df", "grep", "top", 3, "linux", 0),
("What is LVM (Logical Volume Manager) in Linux?", "A tool for managing partitions and configurations.", "A system for managing logical volumes, allowing flexible resizing and management of disk space.", "A utility for formatting filesystems on Linux partitions.", "A command-line utility for syncing the partitions to partition table.", 1, "linux", 0),
("Which command is commonly used to resize an XFS filesystem in Linux?", "resize2fs", "xfs_growfs", "grow_resize2fs", "fsck.xfs", 1, "linux", 0),
("Which command is commonly used to device messages in Linux?", "lsusb", "dmesg", "ifconfig", "lscpu", 1, "linux", 0),
("Which of the following operating systems belong to the RedHat OS Family? Select all that apply.", "Rocky-Linux", "CentOS", "Ubuntu", "Mint", "0,1", "linux", 1),
("What is the best way to restore the /etc/passwd file in Linux after accidental deletion or corruption?", "Reboot the system to single-user mode and manually recreate the /etc/passwd file using a text editor.", "Copy the /etc/passwd- backup file to /etc/passwd.", "Use the useradd commands to recreate the user accounts and passwords individually.", NULL, 1, "linux", 0),
("To grant Davis (and only Davis) full access to John's home directory, which command would you use without losing John's access?", "chmod 777 /home/john", "setfacl -m u:davis:rwx /home/john", "chown davis:davis /home/john", NULL, 1, "linux", 0);

-- C & CPP questions part-1
INSERT INTO questions (question, option1, option2, option3, option4, correct_answers, is_multiple_choice, category) VALUES
("What is the correct syntax to include a header file in C?", "#include <header.h>", "#include 'header.h'", "#include <header>", "#include header.h", 0, 0, "c&cpp"),
("Which of the following is a valid variable declaration in C?", "int 1number;", "int number1;", "int number one;", "int number#1;", 1, 0, "c&cpp"),
("What does the 'printf' function return?", "int", "void", "char", "float", 0, 0, "c&cpp"),
("Which keyword is used to define a constant in C++?", "constant", "define", "const", "final", 2, 0, "c&cpp"),
("What is the main function's return type in C?", "void", "int", "char", "float", 1, 0, "c&cpp"),
("Which operator is used for dynamic memory allocation in C?", "malloc", "alloc", "new", "create", 0, 0, "c&cpp"),
("In C++, which of the following is used for creating a class?", "class ClassName {}", "Class ClassName {}", "create ClassName {}", "define ClassName {}", 0, 0, "c&cpp"),
("What does 'new' do in C++?", "Creates a variable", "Allocates memory", "Defines a class", "Initializes an object", 1, 0, "c&cpp"),
("Which of the following is a valid pointer declaration in C?", "int *ptr;", "int ptr*;", "ptr int*;", "int &ptr;", 0, 0, "c&cpp"),
("What is the output of 'printf(\"%d\", 10 + 20);'?", "30", "1020", "10 + 20", "Error", 0, 0, "c&cpp"),
("Which of the following is a valid C++ comment?", "// This is a comment", "# This is a comment", "/* This is a comment */", "Both 1 and 3", 3, 0, "c&cpp"),
("What is the size of an int on a 32-bit system?", "2 bytes", "4 bytes", "8 bytes", "16 bytes", 1, 0, "c&cpp"),
("Which function is used to find the length of a string in C?", "strlen()", "strlength()", "length()", "sizeof()", 0, 0, "c&cpp"),
("What is the default return type of a function in C if not specified?", "int", "void", "char", "error", 0, 0, "c&cpp"),
("Which operator is used to access members of a structure in C?", "->", ".", ".*", "->*", 1, 0, "c&cpp"),
("What is the purpose of the 'break' statement?", "To exit a loop", "To terminate a program", "To skip the current iteration", "To return a value", 0, 0, "c&cpp"),
("In C++, what is the correct way to declare a destructor?", "~ClassName()", "ClassName~()", "~ClassName;", NULL, 0, 0, "c&cpp"),
("Which of the following is NOT a valid C++ data type?", "int", "float", "double", "decimal", 3, 0, "c&cpp");

-- C & CPP Part-2
INSERT INTO questions (question, option1, option2, option3, option4, correct_answers, is_multiple_choice, category) VALUES
("What does the 'sizeof' operator do?", "Returns the size of a variable", "Returns the size of a data type", "Both 1 and 2", "None of the above", 2, 0, "c&cpp"),
("Which of the following are valid data types in C?", "int", "float", "char", "string", 0, 1, "c&cpp"),
("In C++, which of the following keywords are used for exception handling?", "try", "catch", "throw", "finally", 0, 1, "c&cpp"),
("Which of the following can lead to undefined behavior in C?", "Dereferencing a null pointer", "Using uninitialized variables", "Out of bounds array access", "All of the above", 3, 1, "c&cpp"),
("In C++, which of the following are valid access specifiers?", "public", "private", "protected", "internal", 0, 1, "c&cpp"),
("Which of the following are C standard libraries?", "<stdio.h>", "<stdlib.h>", "<iostream>", "<string.h>", 0, 1, "c&cpp"),
("Which of the following features are supported by C++ but not by C?", "Classes", "Inheritance", "Polymorphism", "Function Overloading", 0, 1, "c&cpp"),
("Which of the following are valid ways to allocate memory in C?", "malloc()", "calloc()", "realloc()", "new", 0, 1, "c&cpp"),
("In C++, which of the following are valid ways to declare a constructor?", "ClassName()", "ClassName(parameters)", "void ClassName()", "ClassName;", 0, 1, "c&cpp"),
("Which of the following statements are true about pointers?", "Pointers can be assigned to NULL", "Pointers can point to functions", "Pointers can be used with arrays", "Pointers can be incremented", 0, 1, "c&cpp"),
("In C++, which of the following can be used to create a constant?", "const", "constexpr", "define", "static", 0, 1, "c&cpp"),
("Which of the following are valid ways to define a macro in C?", "#define MACRO value", "#define MACRO(x) (x + 1)", "#define MACRO(x, y) (x + y)", "macro MACRO = value", 0, 1, "c&cpp"),
("In C++, which of the following are characteristics of a destructor?", "Has the same name as the class", "Cannot take parameters", "Is called automatically", "Can be overloaded", 0, 1, "c&cpp"),
("Which of the following are valid C++ containers?", "vector", "list", "map", "array", 0, 1, "c&cpp"),
("Which of the following are looping constructs in C?", "for", "while", "do-while", "foreach", 0, 1, "c&cpp"),
("Which of the following are valid string handling functions in C?", "strcpy()", "strlen()", "strcat()", "string()", 0, 1, "c&cpp"),
("Which keyword is used to inherit a class in C++?", "inherits", "base", "extends", "public", 3, 0, "c&cpp"),
("What is the purpose of the 'continue' statement?", "To skip to the next iteration", "To exit a loop", "To terminate a program", "None of the above", 0, 0, "c&cpp"),
("What is a valid way to declare a function pointer in C?", "int (*ptr)();", "int ptr();", "void *ptr;", "int &ptr();", 0, 0, "c&cpp"),
("Which of the following is an access specifier in C++?", "public", "private", "protected", "All of the above", 3, 0, "c&cpp"),
("What does 'NULL' represent in C?", "0", "An undefined value", "A memory address", "None of the above", 0, 0, "c&cpp"),
("Which library is required for string manipulation in C?", "<string.h>", "<str.h>", "<string>", "<lib.h>", 0, 0, "c&cpp"),
("What is the output of 'printf(\"%d\", 0.1 + 0.2 == 0.3);'?", "1", "0", "Error", "True", 1, 0, "c&cpp"),
("Which of the following is a valid C++ constructor?", "ClassName()", "void ClassName()", "ClassName[]", "ClassName;", 0, 0, "c&cpp"),
("What is the purpose of the 'this' pointer in C++?", "To refer to the current object", "To call a constructor", "To access base class members", "None of the above", 0, 0, "c&cpp"),
("Which of the following correctly allocates memory for an array of 10 integers?", "int arr[10];", "int *arr = new int[10];", "int *arr = malloc(10 * sizeof(int));", "All of the above", 3, 0, "c&cpp"),
("What is a virtual function in C++?", "A function that is defined in a derived class", "A function that is declared with the keyword 'virtual'", "A function that cannot be overridden", "None of the above", 1, 0, "c&cpp"),
("Which of the following is the correct syntax for a for loop?", "for(int i = 0; i < 10; i++)", "for(int i = 0; i < 10)", "for i in range(10)", "for(int i; i < 10; i++)", 0, 0, "c&cpp"),
("What will happen if you don't use 'return' in the main function?", "The program will not compile", "Undefined behavior", "It returns 0 by default", "It returns an error", 2, 0, "c&cpp"),
("In C++, what is the difference between '==' and '='?", "'==' is for assignment, '=' is for comparison", "'==' is for comparison, '=' is for assignment", "Both are the same", "None of the above", 1, 0, "c&cpp"),
("What is the result of '5 / 2' in C?", "2", "2.5", "2.0", "3", 0, 0, "c&cpp"),
("What is a memory leak?", "Failing to free allocated memory", "Accessing unallocated memory", "Both 1 and 2", "None of the above", 0, 0, "c&cpp"),
("Which of the following can be used to create a constant in C?", "const", "define", "static", "Both 1 and 2", 3, 0, "c&cpp"),
("What is the primary use of the 'void' keyword?", "To indicate no return value", "To declare pointers", "To define data types", "None of the above", 0, 0, "c&cpp"),
("Which operator is used to dereference a pointer?", "*", "&", "->", "^", 0, 0, "c&cpp");

-- AWS questions
INSERT INTO questions (question, option1, option2, option3, option4, correct_answers, category, is_multiple_choice) VALUES
('True or False? Each AWS region is designed to be completely isolated from the other AWS regions', 'True', 'False', '', '', 0, 'aws', 0),
('True or False? Each region has a minimum number of 1 availability zones and the maximum is 4', 'True', 'False', '', '', 1, 'aws', 0),
('What considerations to take when choosing an AWS region for running a new application?', 'The region with most number of Availability Zones', 'The region closest to the AWS global headquarters', 'The region that minimizes latency for your users and complies with data residency regulations', 'The region with the cheapest EC2 pricing overall', 2, 'aws', 0),
('True or False? IAM configuration is defined globally and not per region', 'True', 'False', '', '', 0, 'aws', 0),
('True or False? When creating an AWS account, root account is created by default. This is the recommended account to use and share in your organization', 'True', 'False', '', '', 1, 'aws', 0),
('True or False? Groups in AWS IAM, can contain only users and no other groups', 'True', 'False', '', '', 0, 'aws', 0),
('True or False? Users in AWS IAM, can belong only to a single group', 'True', 'False', '', '', 1, 'aws', 0),
('What is AWS Identity and Access Management (IAM), and which of the following is a feature it provides?', 'It manages EC2 instance performance optimization', 'It provides a firewall to block malicious traffic', 'It allows you to manage access to AWS services and resources securely', 'It is used to automatically scale applications across regions', 2, 'aws', 0),
("True or False? If a user in AWS is using password for authenticating, he doesn't needs to enable MFA", 'True', 'False', '', '', 1, 'aws', 0),
('Which of the following best characterizes the purpose of an IAM Role in AWS?', 'A permanent identity assigned to users for long-term access to AWS services', 'A temporary set of permissions that can be assumed by trusted entities such as AWS services.', 'A mechanism for grouping IAM users under a common set of policies', 'A script used for provisioning access control lists to AWS resources', 1, 'aws', 0),
('In the context of AWS IAM, which of the following statements most accurately describes what a policy is?', 'A YAML-based document that controls access to AWS billing features', 'A configuration file attached to resources that defines their behavior', 'A JSON document that specifies who can assume an IAM role', 'A JSON-based permission document that defines what actions are allowed or denied on specific AWS resources', 3, 'aws', 0),
('A user is unable to access an s3 bucket. What might be the problem?', 'Move the S3 bucket to the user’s default region', 'Attach a policy to the user granting permissions to access the S3 bucket', 'Modify the bucket’s ACL to grant the user read permissions', 'Enable S3 Block Public Access settings on the bucket', 1, 'aws', 0),
('True or False? EC2 is a regional service', 'True', 'False', '', '', 0, 'aws', 0),
('True or False? AMI are built for specific region', 'True', 'False', '', '', 0, 'aws', 0),
('In the EC2 instance type name m5.large, what does each component represent?', 'M = Generation 5=Instance Class, Large=Storage Size', 'M = Memory Optimized, 5 = Burstable performance tier, Large = network throughput', 'M = Instance Class, 5 = Generation, Large = Size of the instance', 'M = Reserved Instance Type, 5 = core count, Large = EBS Volume size', 2, 'aws', 0),
('True or False? The following are instance types available for a user in AWS:', 'Compute optimized', 'Network optimized', 'Web Optimized', '', 2, 'aws', 0),
('What happens to EBS volumes when an EC2 instance is terminated?', 'All attached EBS volumes are deleted immediately by default.', 'By default, the root volume is deleted, but any additional EBS volumes persist unless specified otherwise.', 'By default, both the root and any additional EBS volumes are preserved.', 'All EBS volumes, including snapshots, are retained and billed until manually deleted.', 1, 'aws', 0),
('What happens to the attached EBS volumes when an EC2 instance is stopped (not terminated)?', 'All EBS volumes are deleted, including the root volume', 'The root volume is deleted, but data volumes remain intact', 'The EBS volumes are detached and archived to S3', 'The EBS volumes remain intact and will be available when the instance is started again', 3, 'aws', 0),
('True or False? EBS volumes are locked to a specific availability zone', 'True', 'False', '', '', 0, 'aws', 0),
('What are the use cases for using EBS snapshots?', 'Create a point-in-time copy of an EBS volume that can be used to create a new volume in a different Availability Zone or Region.', 'Immediately restore an EBS volume to a previous state without any downtime.', 'Provide a continuous, real-time backup of an EBS volume.', 'Directly replace a failed EBS volume with a snapshot without any data loss or service interruption.', 0, 'aws', 0),
('Under what condition can a single EBS volume be attached to multiple EC2 instances simultaneously?', 'When using Provisioned IOPS SSD (io1 or io2) volumes with Multi-Attach enabled', 'When using general purpose SSD (gp3) volumes', 'When using standard magnetic volumes', 'When launching instances in the same Availability Zone without IAM restrictions', 0, 'aws', 0),
('True or False? EBS is a network drive hence, it requires network connectivity', 'True', 'False', '', '', 0, 'aws', 0),
('True or False? EFS is locked into a single availability zone', 'True', 'False', '', '', 1, 'aws', 0),
('Which of the following are common use cases for using Amazon EFS (Elastic File System)?', 'Hosting container images and AMIs for reuse across Regions', 'Data sharing, web serving, and content management across multiple EC2 instances', 'Temporary high-speed block storage for individual EC2 instances', 'Object-level storage for static websites with global access', 1, 'aws', 0),
('True or False? EFS only compatible with Linux based AMI', 'True', 'False', '', '', 0, 'aws', 0),
("True or False? EFS requires the user to perform capacity planning as it doesn't scales automatically", 'True', 'False', '', '', 1, 'aws', 0),
('True or False? Reserved instance has to be used for a minimum of 1 year', 'True', 'False', '', '', 0, 'aws', 0),
('You need to launch an EC2 instance for a short-term project, and it is critical that the workload is not interrupted. Which EC2 pricing model is the most appropriate?', 'Reserved Instances', 'Spot Instances', 'On-Demand Instances', 'Savings Plans', 2, 'aws', 0),
('True or False? One security group can be attached to multiple instances', 'True', 'False', '', '', 0, 'aws', 0),
('True or False? Security groups are not locked down to a region and VPC', 'True', 'False', '', '', 1, 'aws', 0),
("In the context of AWS EC2, what does 'bootstrapping' refer to and how is it typically used?", 'Encrypting the EBS volumes before launching the instance', 'Creating a snapshot of the root volume before instance shutdown', 'Attaching IAM roles to an instance for temporary access credentials', 'Automatically configuring an instance at launch using user data scripts', 3, 'aws', 0),
("True or False? It's possible to have multiple VPCs in one region", 'True', 'False', '', '', 0, 'aws', 0),
('True or False? One or more VPCs can be attached to one Internet Gateway', 'True', 'False', '', '', 1, 'aws', 0),
('After restarting your EC2 instance, you notice that the public IP address has changed. How can you ensure the IP address remains the same across restarts?', 'Use an Elastic Load Balancer (ELB) in front of the instance', 'Stop using public IPs and switch to private IPs only', 'Assign an Elastic IP to the instance', 'Change the instance type to a reserved instance', 2, 'aws', 0),
("True or False? In AWS Lambda, you are charged as long as a function exists, regardless of whether it's running or not", 'True', 'False', '', '', 1, 'aws', 0),
('True or False? Basic lambda permissions allow you only to upload logs to Amazon CloudWatch Logs', 'True', 'False', '', '', 0, 'aws', 0),
('What must be done to make an EC2 instance part of an Amazon ECS (Elastic Container Service) cluster?', 'Attach an IAM role with read-only S3 permissions', 'Install the ECS agent and configure the instance to join the cluster', 'Enable auto-scaling on the EC2 instance', 'Convert the EC2 instance to a Lambda function', 1, 'aws', 0),
('What features suits CloudWatch operation?', 'CloudWatch does not support custom metrics', 'collect and monitor operating system and application generated log files', 'CloudTrail generates logs automatically when AWS account is activated', 'AWS services automatically create logs for CloudWatch', 1, 'aws', 0),
('What is required to ensure that new EC2 instances launched by an Auto Scaling Group are correctly configured?', 'Tagging the instances with a specific key', 'Creating a CloudFormation template', 'Defining a Launch Template', 'Enabling S3 bucket access on the instance', 2, 'aws', 0),
('What happens when an EC2 instance registered with an ELB through an ASG fails its health check?', 'ELB will reboot the instance automatically', 'The instance will be manually deregistered by AWS support', 'ELB will send an SNS alert but take no action', 'ASG will terminate the instance and launch a new one', 3, 'aws', 0),
('True or False? RDS read replicas are asynchronous?', 'True', 'False', '', '', 0, 'aws', 0),
('True or False? Amazon RDS supports MongoDB?', 'True', 'False', '', '', 1, 'aws', 0),
('What is the primary benefit of using RDS read replicas?', 'To enable automatic failover in case the primary database fails', 'To distribute read-heavy workloads and improve application performance', 'To reduce storage costs by compressing database files', 'To encrypt data at rest without performance impact', 1, 'aws', 0),
('True or False? Migrating AWS RDS from single AZ to multi AZ is an operation with downtime (meaning there is a need to stop the DB)', 'True', 'False', '', '', 1, 'aws', 0),
('What is the main difference between a CNAME record and an Alias record in AWS Route 53?', 'CNAME records can only point to IP addresses, while Alias records can only point to domain names', 'Alias records are slower to resolve than CNAME records', 'CNAME records provide better security than Alias records', 'CNAME is used for mapping one hostname to any other hostname while Alias is used to map an hostname to an AWS resource.', 3, 'aws', 0),
('Suppose you need to route % of your traffic to Instance A and % of your traffic to Instance B. Which Route 53 routing policy would you choose?', 'Simple Routing Policy', 'Latency-based Routing Policy', 'Weighted Routing Policy', 'Geolocation Routing Policy', 2, 'aws', 0),
('You need persistent shared storage between your containers where some are running in Fargate and some in ECS EC2. The storage should be accessible across multiple Availability Zones. What would you use?', 'Amazon EBS volumes', 'Docker local volumes', 'Amazon S3 buckets', 'Amazon EFS file system', 3, 'aws', 0);

-- linux part-2
INSERT INTO questions (question, option1, option2, option3, option4, correct_answers, category, is_multiple_choice) VALUES
('What command is used to display the disk usage of files and directories in a human-readable format?', 'df -h', 'du -h', 'ls -lh', 'fdisk -l', 1, 'linux', 0),
("Which command allows you to change the permissions of a file named 'data.txt' to read and write for the owner only?", 'chmod 600 data.txt', 'chmod 700 data.txt', 'chmod 644 data.txt', 'chmod 755 data.txt', 0, 'linux', 0),
('What is the purpose of the /etc/fstab file in Linux?', 'Stores user passwords', 'Defines filesystem mount points', 'Lists active processes', 'Configures network interfaces', 1, 'linux', 0),
('Which command shows the currently running processes with their process IDs and resource usage?', 'ps aux', 'top', 'htop', 'All of the above', 3, 'linux', 0),
('How do you terminate a process with PID 1234 using a standard signal?', 'kill -9 1234', 'kill -15 1234', 'stop 1234', 'end 1234', 1, 'linux', 0),
('Which file contains the configuration for the default shell for users?', '/etc/passwd', '/etc/shadow', '/etc/shells', '/etc/profile', 0, 'linux', 0),
("What command is used to create a new user named 'john' without a private group?", 'useradd -m john', 'adduser -h john', 'useradd -d john', 'useradd -N john', 3, 'linux', 0),
('Which command displays the network interfaces and their configurations?', 'ifconfig', 'netstat -i', 'ip addr', 'Both a and c', 3, 'linux', 0),
('What does the command crontab -e do?', 'Lists all cron jobs', 'Edits the crontab file for the current user', 'Removes all cron jobs', 'Displays the cron daemon status', 1, 'linux', 0),
('Which directory typically contains log files in a Linux system?', '/var/log', '/etc/log', '/log', '/usr/log', 0, 'linux', 0),
('What is the purpose of the sudo command?', 'Runs a command as another user', 'Runs a command with superuser privileges', 'Switches to the root user', 'Edits system configuration files', 1, 'linux', 0),
('Which command checks the integrity of a filesystem?', 'fsck', 'fdisk', 'mkfs', 'parted', 0, 'linux', 0),
('What is the default port for SSH connections?', '21', '22', '23', '80', 1, 'linux', 0),
('Which command is used to update the package list in a Debian-based system?', 'apt-get update', 'yum update', 'dnf refresh', 'pacman -Sy', 0, 'linux', 0),
('What does the grep command do?', 'Searches for files in a directory', 'Searches for text patterns in files', 'Compares two files', 'Edits text files', 1, 'linux', 0),
('Which file is used to configure DNS resolution in Linux?', '/etc/hosts', '/etc/resolv.conf', '/etc/networks', '/etc/dns.conf', 1, 'linux', 0),
('What command displays the kernel version of a Linux system?', 'uname -r', 'kernel -v', 'uname -p', 'Both a and c', 0, 'linux', 0),
('What does the chown command do?', 'Changes file permissions', 'Changes file ownership', 'Changes file group', 'Both b and c', 1, 'linux', 0),
('Which command restarts the networking service on a systemd-based system?', 'systemctl restart networking', 'service network restart', 'nmcli connection ens160 down', 'Both a and c', 0, 'linux', 0),
('What is the purpose of the /etc/sudoers file?', 'Stores user passwords', 'Configures sudo permissions', 'Defines shell aliases', 'Lists system services', 1, 'linux', 0),
('Which command is used to display the current working directory?', 'pwd', 'ls', 'cd', 'dir', 0, 'linux', 0),
('What is the purpose of the `tar` command?', 'Archive files', 'Delete files', 'Encrypt files', 'Rename files', 0, 'linux', 0),
('Which user account has unrestricted access to all files and commands in Linux?', 'admin', 'root', 'superuser', 'sudo', 1, 'linux', 0),
('What does the `man` command do?', 'Shows system manual pages', 'Runs a process', 'Manages users', 'Creates files', 0, 'linux', 0),
('Which command is used to count the number of lines in a file?', 'wc -l', 'count', 'nl', 'linecount', 0, 'linux', 0),
('How do you append text to a file using the echo command?', "echo 'text' > file", "echo 'text' >> file", "append 'text' file", "echo file 'text'", 1, 'linux', 0),
('What is the function of the `touch` command?', 'Edit file', 'Remove file', 'Create empty file', 'Search file', 2, 'linux', 0),
('Which command will recursively list all files and subdirectories?', 'ls -a', 'ls -R', 'ls -l', 'ls -r', 1, 'linux', 0),
('How do you switch to the root user?', 'sudo su', 'login root', 'sudo login', 'root', 0, 'linux', 0),
('Which command is used to find files by name?', 'find', 'locate', 'search', 'which', 0, 'linux', 0),
('What is the default shell in most Linux distributions?', 'bash', 'sh', 'zsh', 'ksh', 0, 'linux', 0),
('Which key combination is used to suspend a foreground process?', 'Ctrl+Z', 'Ctrl+C', 'Ctrl+X', 'Ctrl+D', 0, 'linux', 0),
('What is the purpose of `df` command?', 'Disk free space', 'Directory listing', 'Device info', 'File system type', 0, 'linux', 0),
('Which Linux command is used to change file names?', 'mv', 'cp', 'rename', 'change', 0, 'linux', 0),
('What does `ls -l` show?', 'Long listing format', 'Hidden files', 'Directory size', 'User permissions only', 0, 'linux', 0),
('What does `chmod 755` do?', 'Read-write-execute for owner, read-execute for others', 'Full access for everyone', 'No access for group', 'Read-write only', 0, 'linux', 0),
('What is the role of `/etc/shadow`?', 'Stores encrypted user passwords', 'Lists users', 'Contains shell info', 'Stores log files', 0, 'linux', 0),
('Which command displays all users currently logged in?', 'who', 'users', 'w', 'All of the above', 3, 'linux', 0),
('What is the default location of user home directories?', '/home', '/usr', '/users', '/etc', 0, 'linux', 0),
('Which tool is used to configure runlevels in older Linux systems?', 'init', 'systemctl', 'update-rc.d', 'rcconf', 0, 'linux', 0),
('Which command is used to test network connectivity?', 'ping', 'ifconfig', 'netstat', 'ssh', 0, 'linux', 0),
('What does the `alias` command do?', 'Creates shortcuts for commands', 'Deletes files', 'Shows disk usage', 'Manages services', 0, 'linux', 0),
('Which command displays the current date and time?', 'date', 'time', 'clock', 'cal', 0, 'linux', 0),
('How do you reboot a Linux system from the command line?', 'reboot', 'shutdown -r now', 'init 6', 'All of the above', 3, 'linux', 0),
('What is the difference between `>` and `>>` in Linux?', '`>` overwrites, `>>` appends', '`>` appends, `>>` overwrites', 'Both are same', 'None', 0, 'linux', 0),
('How to check memory usage in Linux?', 'free -h', 'top', 'vmstat', 'All of the above', 3, 'linux', 0),
('What does `tail -n 10 logfile.txt` do?', 'Shows last 10 lines of logfile.txt', 'Deletes first 10 lines', 'Prints first 10 lines', 'Counts 10 lines', 0, 'linux', 0),
('How do you list hidden files?', 'ls -a', 'ls -h', 'ls -H', 'ls --hidden', 0, 'linux', 0),
('What is the full form of LVM in Linux?', 'Logical Volume Manager', 'Linux Virtual Memory', 'Logical Virtual Machine', 'Large Volume Mode', 0, 'linux', 0),
('What does the `history` command show?', 'List of previous commands', 'System logs', 'File history', 'All of the above', 0, 'linux', 0);

-- devops part-1
INSERT INTO questions (question, option1, option2, option3, option4, correct_answers, category, is_multiple_choice) VALUES
("How do you create and switch to a new branch called 'feature-x' in Git?", 'git branch feature-x', 'git checkout -b feature‑x', 'git switch feature‑x', 'git branch ‑c feature‑x', 1, 'devops', 0),
("How do you resolve a merge conflict in Git?", "Use 'git merge --abort'", "Edit the conflicting files, then 'git add' and 'git commit'", "Use 'git rebase --continue'", 'Delete the conflicting branch', 1, 'devops', 0),
("What is a pull request in GitHub?", 'A request to merge changes from one branch to another', 'A request to clone a repository', 'A request to create a new branch', 'A request to delete a repository', 0, 'devops', 0),
("What is CI/CD in DevOps?", 'Continuous Integration and Continuous Deployment', 'Code Inspection and Continuous Delivery', 'Continuous Improvement and Continuous Development', 'Cloud Integration and Code Deployment', 0, 'devops', 0),
("Which tool is commonly used for continuous integration?", 'Jenkins', 'Ansible', 'Docker', 'Kubernetes', 0, 'devops', 0),
("What does the 'docker build' command do?", 'Runs a Docker container', 'Builds a Docker image from a Dockerfile', 'Deletes a Docker image', 'Updates Docker', 1, 'devops', 0),
("How do you list all running Docker containers?", 'docker list', 'docker ps', 'docker show', 'docker running', 1, 'devops', 0),
("Which command is used to deploy a Kubernetes configuration file?", 'kubectl apply -f filename.yaml', 'kube apply', 'kubectl create config', 'kubectl start -f filename.yaml', 0, 'devops', 0),
("What is Infrastructure as Code (IaC)?", 'Using programming scripts to write application code', 'Manually configuring servers', 'Provisioning and managing infrastructure using code', 'Developing software manually', 2, 'devops', 0),
("Which tool is used for IaC?", 'Terraform', 'Jenkins', 'Nagios', 'Git', 0, 'devops', 0),
("What does YAML stand for in DevOps context?", 'Yet Another Markup Language', 'You Are Markup Language', 'Your Application Machine Language', 'None of the above', 0, 'devops', 0),
("Which tool is commonly used for configuration management?", 'Ansible', 'Kubernetes', 'Jenkins', 'Docker', 0, 'devops', 0),
("How do you initialize a new Git repository?", 'git start', 'git init', 'git new', 'git repo', 1, 'devops', 0),
("What is the purpose of a Dockerfile?", 'To run Docker images', 'To configure a Kubernetes cluster', 'To define instructions for building a Docker image', 'To list all Docker commands', 2, 'devops', 0),
("What is Helm in Kubernetes?", 'A monitoring tool', 'A networking tool', 'A package manager for Kubernetes', 'A Docker alternative', 2, 'devops', 0),
("Which tool is used to monitor applications and infrastructure in real-time?", 'Grafana', 'Git', 'Jenkins', 'Terraform', 0, 'devops', 0),
("How do you clone a Git repository?", 'git fetch', 'git clone [repo_url]', 'git commit', 'git copy', 1, 'devops', 0),
("Which command is used to check the status of a Git repository?", 'git check', 'git update', 'git status', 'git info', 2, 'devops', 0),
("What is a pod in Kubernetes?", 'A container image', 'A node', 'A smallest deployable unit in Kubernetes', 'A virtual machine', 2, 'devops', 0),
("How do you remove a Docker container?", 'docker remove [container_id]', 'docker rm [container_id]', 'docker delete [container_id]', 'docker kill [container_id]', 1, 'devops', 0),
("What is Jenkins pipeline?", 'A way to monitor servers', 'A CI/CD automation workflow', 'A container orchestration tool', 'An OS deployment tool', 1, 'devops', 0),
("How do you run a playbook in Ansible?", 'ansible-run', 'ansible-playbook [filename]', 'ansible-start', 'ansible-execute', 1, 'devops', 0),
("What is the role of Git in DevOps?", 'Infrastructure provisioning', 'Version control and collaboration', 'Container management', 'Monitoring', 1, 'devops', 0),
("How do you start a Jenkins job manually?", "Click 'Build Now'", "Run 'jenkins start job'", "Use 'start‑job' in CLI", 'Jobs run automatically only', 0, 'devops', 0),
("What is a service in Kubernetes?", 'A background daemon', 'An API object to expose a set of pods', 'A container registry', 'A CLI tool', 1, 'devops', 0),
("Which command installs Terraform on Linux?", 'apt install terraform', 'yum terraform', 'terraform install', 'install terraform‑cli', 0, 'devops', 0),
("Which file stores Terraform configuration?", 'terraform.tf', 'config.yaml', 'main.json', 'infra.txt', 0, 'devops', 0),
("What is Blue-Green Deployment?", 'Testing feature branches', 'Using alternate infrastructure for updates', 'An approach to minimize downtime during deployment', 'Kubernetes scaling strategy', 2, 'devops', 0),
("Which plugin is used in Jenkins to define jobs as code?", 'Job DSL', 'Job Writer', 'CodeJob', 'JobScript', 0, 'devops', 0),
("Which Kubernetes object maintains a desired number of pods?", 'Deployment', 'Service', 'Namespace', 'Ingress', 0, 'devops', 0),
("Which command is used to scale a deployment to 5 replicas in Kubernetes?", 'kubectl set replicas deployment my‑deploy 5', 'kubectl scale deployment my‑deploy --replicas=5', 'kubectl resize my‑deploy 5', 'kubectl update replicas 5', 1, 'devops', 0),
("What is the function of the .gitignore file?", 'To ignore Git errors', 'To ignore specific files from being tracked by Git', 'To commit all changes', 'To reset the Git index', 1, 'devops', 0),
("What is Prometheus used for?", 'Logging', 'Version Control', 'Monitoring and alerting', 'Containerization', 2, 'devops', 0),
("Which DevOps tool helps automate software builds, tests, and deployments?", 'Jenkins', 'Docker', 'Git', 'Helm', 0, 'devops', 0),
("What command shows the logs of a running pod in Kubernetes?", 'kubectl logs [pod‑name]', 'kubectl show [pod‑name]', 'kube logs [pod]', 'kubectl pod logs [name]', 0, 'devops', 0),
('What is a key principle of DevOps?', 'Strict separation of development and operations teams', 'Collaboration and communication between development and operations', 'Prioritizing documentation over automation', 'Using only proprietary tools for deployment', 1, 'devops', 0),
('What is the primary focus of Agile methodology?', 'Continuous delivery of infrastructure', 'Iterative and incremental software development', 'Centralized team management', 'Long‑term planning with fixed requirements', 1, 'devops', 0),
('Which of the following is a benefit of DevOps?', 'Increased silos between teams', 'Faster delivery of software through automation', 'Reduced need for testing', 'Longer deployment cycles', 1, 'devops', 0),
('What is a common Agile framework used for project management?', 'Scrum', 'Waterfall', 'Kanban', 'Both a and c', 3, 'devops', 0),
('How does DevOps differ from Agile in terms of scope?', 'DevOps focuses only on development, Agile on operations', 'DevOps encompasses development and operations, Agile focuses on development', 'Agile includes infrastructure management, DevOps does not', 'Both focus solely on software development', 1, 'devops', 0),
('What is a key advantage of Agile''s iterative approach?', 'Fixed requirements throughout the project', 'Ability to adapt to changing requirements', 'Elimination of all testing phases', 'Reduced need for customer feedback', 1, 'devops', 0),
('Which tool is commonly used for continuous integration in DevOps?', 'Docker', 'Ansible', 'CircleCI', 'Terraform', 2, 'devops', 0),
('What is a potential drawback of DevOps?', 'Improved collaboration between teams', 'High initial setup cost for automation tools', 'Faster time to market', 'Enhanced system reliability', 1, 'devops', 0),
('In Agile, what is the purpose of a "sprint"?', 'To deploy infrastructure changes', 'To complete a set of tasks within a fixed time frame', 'To configure network settings', 'To manage server hardware', 1, 'devops', 0),
('Which DevOps practice helps ensure consistent environments across development, testing, and production?', 'Infrastructure as Code (IaC)', 'Manual server configuration', 'Waterfall development', 'Ad-hoc deployments', 0, 'devops', 0),
('What is a key difference between Agile and DevOps in terms of team focus?', 'Agile emphasizes customer collaboration, DevOps emphasizes automation', 'Agile focuses on automation, DevOps on customer feedback', 'Both focus equally on infrastructure management', 'Agile avoids iterative development, DevOps embraces it', 0, 'devops', 0),
('What is a benefit of using Kanban in Agile?', 'Fixed‑length sprints for all tasks', 'Visualizing workflow to identify bottlenecks', 'Elimination of all planning phases', 'Mandatory use of proprietary tools', 1, 'devops', 0),
('Which DevOps tool is primarily used for container orchestration?', 'Jenkins', 'Kubernetes', 'Ansible', 'Puppet', 1, 'devops', 0),
('How does DevOps improve software delivery compared to traditional methods?', 'By enforcing manual testing for all releases', 'By automating build, test, and deployment processes', 'By increasing development cycle time', 'By reducing collaboration between teams', 1, 'devops', 0),
('How does AWS enhance the use of open‑source DevOps tools like Kubernetes when deployed on Amazon EKS?', 'By restricting access to container orchestration features', 'By providing managed infrastructure, reducing the operational overhead of cluster management', 'By limiting integration with other AWS services', 'By requiring manual updates to Kubernetes versions', 1, 'devops', 0),
('What is a key benefit of running open‑source DevOps tools like Jenkins on AWS EC2 instances?', 'Limited scalability due to fixed instance sizes', 'Ability to scale compute resources dynamically to handle varying CI/CD workloads', 'Requirement for manual hardware maintenance', 'Incompatibility with open‑source plugins', 1, 'devops', 0);

-- aws question part‑2
INSERT INTO questions (question, option1, option2, option3, option4, correct_answers, category, is_multiple_choice) VALUES
('What does EC2 stand for in AWS?', 'Elastic Cloud Compute', 'Elastic Compute Cloud', 'Elastic Cloud Cluster', 'Elastic Control Cloud', 1, 'aws', 0),
('Which AWS service is used for object storage?', 'EBS', 'EC2', 'S3', 'RDS', 2, 'aws', 0),
('What is the purpose of Amazon Route 53?', 'Monitoring', 'Content delivery', 'Domain Name System (DNS) service', 'Security scanning', 2, 'aws', 0),
('Which service is used for serverless computing in AWS?', 'EC2', 'Lambda', 'ECS', 'RDS', 1, 'aws', 0),
('What does IAM stand for in AWS?', 'Internal Account Management', 'Identity Access Machine', 'Identity and Access Management', 'Internet Access Method', 2, 'aws', 0),
('Which service allows you to run containerized applications?', 'AWS Lambda', 'Amazon S3', 'Amazon ECS', 'Amazon RDS', 2, 'aws', 0),
('What type of database is Amazon RDS?', 'Key‑value store', 'Relational database', 'NoSQL database', 'In‑memory database', 1, 'aws', 0),
('Which AWS service can be used to send email?', 'SES', 'SNS', 'SQS', 'EC2', 0, 'aws', 0),
('Which AWS service provides scalable message queuing?', 'Amazon SNS', 'Amazon SES', 'Amazon MQ', 'Amazon SQS', 3, 'aws', 0),
('Which storage type offers block‑level storage in AWS?', 'S3', 'Glacier', 'EBS', 'CloudFront', 2, 'aws', 0),
('What is the main use of AWS CloudTrail?', 'Load balancing', 'Monitoring EC2 usage', 'Tracking user activity and API usage', 'Logging S3 uploads', 2, 'aws', 0),
('What does AWS VPC stand for?', 'Virtual Private Cloud', 'Virtual Public Compute', 'Variable Private Cloud', 'Verified Public Cloud', 0, 'aws', 0),
('What AWS service can be used for automatic scaling?', 'CloudWatch', 'Auto Scaling', 'Route 53', 'SNS', 1, 'aws', 0),
('What AWS service is used for monitoring resources?', 'CloudTrail', 'Auto Scaling', 'CloudWatch', 'EC2', 2, 'aws', 0),
('What is AWS CloudFront?', 'Load balancer', 'DNS resolver', 'Content Delivery Network (CDN)', 'Monitoring service', 2, 'aws', 0),
('Which service helps you create and manage a virtual network?', 'EC2', 'VPC', 'Route 53', 'S3', 1, 'aws', 0),
('What type of storage is Amazon Glacier?', 'Block storage', 'Hot data storage', 'Cold data archive', 'File storage', 2, 'aws', 0),
('AWS Free Tier is available for how many months?', '3 months', '6 months', '12 months', 'Lifetime', 2, 'aws', 0),
('Which AWS database is a managed NoSQL service?', 'RDS', 'DynamoDB', 'Redshift', 'Aurora', 1, 'aws', 0),
('AWS Regions are divided into:', 'Data Centers', 'Availability Zones', 'Clusters', 'Instances', 1, 'aws', 0);
